---
- name: Include vars
  ansible.builtin.include_vars: ../vars/ah_ee_images.yml
  tags:
    - ee_images

- name: Import ah_configuration role
  ansible.builtin.import_role:
    name: redhat_cop.ah_configuration.ee_image
  tags:
    - ee_images
...
