---
- name: Include vars
  include_vars: ../vars/ah_ee_registry_sync.yml
  tags:
    - regsync

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.ee_registry_sync
  tags:
    - regsync
...
