---

# Create EDA Controller Credential
- name: Add EDA Controller credential
  ansible.eda.credential:
    name:                 "{{ __credential_item.name }}"
    new_name:             "{{ __credential_item.new_name | default(omit) }}"
    description:          "{{ __credential_item.description | default(omit) }}"
    organization_name:    "{{ __credential_item.organization | default(omit) }}"
    credential_type_name: "{{ __credential_item.credential_type | default('GitHub Personal Access Token') }}"
    inputs:               "{{ __credential_item.inputs | default(omit) }}"
    state:                "{{ __credential_item.state | default(eda_state | default('present')) }}"
    controller_host:      "{{ platform_hostname}}"
    eda_username:  "{{ eda_username | default(omit) }}"
    controller_password:  "{{ platform_password | default(omit) }}"
    validate_certs:       "{{ platform_validate_certs| default(omit) }}"
    request_timeout:      "{{ platform_request_timeout | default(omit) }}"
  loop: "{{ eda_credentials }}"
  loop_control:
    loop_var: "__credential_item"
  no_log: "{{ eda_configuration_credential_secure_logging }}"
  async: 1000
  poll: 0
  register: __credentials_job_async
  changed_when: not __credentials_job_async.changed
  vars:
    ansible_async_dir: '{{ platform_configuration_async_dir }}'

- name: "Create credential | Wait for finish the credential creation"
  ansible.builtin.async_status:
    jid: "{{ __credentials_job_async_result_item.ansible_job_id }}"
  register: __credentials_job_async_result
  until: __credentials_job_async_result.finished
  retries: "{{ eda_configuration_credential_async_retries }}"
  delay: "{{ eda_configuration_credential_async_delay }}"
  loop: "{{ __credentials_job_async.results }}"
  loop_control:
    loop_var: __credentials_job_async_result_item
  when: __credentials_job_async_result_item.ansible_job_id is defined
  no_log: "{{ eda_configuration_credential_secure_logging }}"
  vars:
    ansible_async_dir: '{{ platform_configuration_async_dir }}'
...
