---
argument_specs:
  main:
    short_description: An Ansible Role to create execution environment images in Automation Hub.
    options:
      ah_ee_images:
        default: []
        required: false
        description: Data structure describing your ee images to manage.
        type: list
        elements: dict

      # Async variables
      ah_configuration_ee_image_async_retries:
        default: "{{ aap_configuration_async_retries | default(50) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 50
        required: false
        description: This variable sets number of retries across all roles as a default.
      ah_configuration_ee_image_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to  `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      ah_configuration_ee_image_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive role tasks in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      ah_path_prefix:
        required: false
        description: The path for the Automation Hub API. Usually galaxy or automation-hub unless custom set in AH settings.
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_request_timeout:
        default: 10
        required: false
        description: Specify the timeout Ansible should use in requests to the Ansible Automation Platform Server.
        type: float
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
