---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_hostname: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# ah_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the Automation Hub namespace
ah_namespaces: []
# possible fields:
#  - name: "namespace_name" # mandatory
#    company: Redhat
#    email: user@example.com
#    avatar_url: image_url # optional
#    description: string # optional
#    resources: "markdown file in a string" # optional
#    links: #both fields mandatory when using links
#      - name: "Link Text"
#        url: "url"
#    groups: #both fields mandatory when using groups
#      - name: "group_name"
#        object_permissions: #Possible options below
#          - # mandatory, choices: change_namespace, upload_to_namespace

ah_configuration_namespace_secure_logging: "{{ ah_configuration_secure_logging | default(false) }}"
ah_configuration_namespace_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
ah_configuration_namespace_async_delay: "{{ ah_configuration_async_delay | default(1) }}"
...
