---
- name: Add an inventory source
  tower_inventory_source:
    name:                                 "{{ source.name | mandatory }}"
    new_name:                             "{{ source.new_name | default(omit, true) }}"
    description:                          "{{ source.description | default(omit, true) }}"
    inventory:                            "{{ source.inventory.name | default( source.inventory ) | mandatory }}"
    organization:                         "{{ source.inventory.organization.name | default( source.organization | default(omit, true)) }}"
    source:                               "{{ source.source | mandatory }}"
    source_path:                          "{{ source.source_path | default(omit, true) }}"
    source_script:                        "{{ source.source_script | default(omit, true) }}"
    source_vars:                          "{{ source.source_vars | default(omit, true) }}"
    enabled_var:                          "{{ source.enabled_var | default(omit, true) }}"
    enabled_value:                        "{{ source.enabled_value | default(omit, true) }}"
    host_filter:                          "{{ source.host_filter | default(omit, true) }}"
    credential:                           "{{ source.credential | default(omit, true) }}"
    execution_environment:                "{{ source.execution_environment | default(omit, true) }}"
    overwrite:                            "{{ source.overwrite | default('false') }}"
    overwrite_vars:                       "{{ source.overwrite_vars | default('false') }}"
    custom_virtualenv:                    "{{ source.custom_virtualenv | default(omit, true) }}"
    timeout:                              "{{ source.timeout | default(omit, true) }}"
    verbosity:                            "{{ source.verbosity | default(omit, true) }}"
    update_on_launch:                     "{{ source.update_on_launch | default(omit, true) }}"
    update_cache_timeout:                 "{{ source.update_cache_timeout | default(omit, true) }}"
    source_project:                       "{{ source.source_project.name | default( source.source_project | default(omit, true)) }}"
    update_on_project_update:             "{{ source.update_on_project_update | default('false') }}"
    state:                                "{{ source.state | default(tower_state | default('present')) }}"
    notification_templates_started:       "{{ source.notification_templates_started | default(source.related.notification_templates_started | default([]) | map(attribute='name') | list ) }}"
    notification_templates_success:       "{{ source.notification_templates_success | default(source.related.notification_templates_success | default([]) | map(attribute='name') | list ) }}"
    notification_templates_error:         "{{ source.notification_templates_error | default(source.related.notification_templates_error | default([]) | map(attribute='name') | list ) }}"
    tower_config_file:                    "{{ tower_config_file | default(omit, true) }}"
    tower_host:                           "{{ tower_hostname | default(omit, true) }}"
    tower_username:                       "{{ tower_username | default(omit, true) }}"
    tower_password:                       "{{ tower_password | default(omit, true) }}"
    tower_oauthtoken:                     "{{ tower_oauthtoken | default(omit, true) }}"
    validate_certs:                       "{{ tower_validate_certs | default('true') }}"
  loop: "{{ tower_inventory_sources }}"
  loop_control:
    loop_var: source
  no_log: "{{ tower_configuration_inventory_sources_secure_logging }}"
...
