---
argument_specs:
  main:
    short_description: An Ansible Role to create authenticators on automation platform gateway.
    options:
      gateway_authenticators:
        description: Data structure describing your authenticators
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of the resource
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          slug:
            type: str
            description: |
              An immutable identifier for the authenticator
              Must be unique
          enabled:
            type: bool
            default: false
            description: Enable/Disable the authenticator
          create_objects:
            type: bool
            default: true
            description: Allow authenticator to create objects (users, teams, organizations)
          remove_users:
            type: bool
            default: true
            description: When a user authenticates from this source should they be removed from any other groups they were previously added to
          configuration:
            type: dict
            default: {}
            description: The required configuration for this source
          type:
            type: str
            description: The type of authentication service this is
          order:
            type: int
            description: The order in which an authenticator will be tried. This only pertains to username/password authenticators defaults to 1 (by API)
          state:
            default: "{{ platform_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      gateway_authenticators_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_authenticators_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      gateway_authenticators_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
