---

#Create Job Template
- name: Add Tower ***********
  awx.awx.tower_***********:
    name:                           "{{ ***********_item.name }}"
    new_name:                       "{{ ***********_item.new_name | default(omit) }}"
    description:                    "{{ ***********_item.description | default('') }}"
    
    





    tower_username:                 "{{ tower_username | default(omit) }}"
    tower_password:                 "{{ tower_password | default(omit) }}"    
    tower_oauthtoken:               "{{ tower_oauthtoken | default(omit) }}"
    tower_host:                     "{{ tower_server }}"
    tower_config_file:              "{{ tower_config_file | default(omit) }}"
    validate_certs:                 "{{ tower_validate_certs | default('yes') }}"
  loop: "{{ tower_************ }}"
  loop_control:
    loop_var: ***********_item  
  no_log: "{{ tower_configuration_*******_secure_logging }}"
  when: tower_************ is defined