---
- name: Add Controller Schedule
  schedule:
    name:                           "{{ __controller_schedule_item.name | mandatory }}"
    new_name:                       "{{ __controller_schedule_item.new_name | default(omit, true) }}"
    description:                    "{{ __controller_schedule_item.description | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    rrule:                          "{{ __controller_schedule_item.rrule | mandatory }}"
    extra_data:                     "{{ __controller_schedule_item.extra_data | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value={}, omit_value=omit), true) }}"
    inventory:                      "{{ __controller_schedule_item.inventory | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    credentials:                    "{{ __controller_schedule_item.credentials | default(omit, true) }}"
    scm_branch:                     "{{ __controller_schedule_item.scm_branch | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    execution_environment:          "{{ __controller_schedule_item.execution_environment.name | default(__controller_schedule_item.execution_environment | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true)) }}"
    forks:                          "{{ __controller_schedule_item.forks | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=0, omit_value=omit), true) }}"
    instance_groups:                "{{ __controller_schedule_item.instance_groups | default(omit, true) }}"
    job_slice_count:                "{{ __controller_schedule_item.job_slice_count | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=1, omit_value=omit), true) }}"
    labels:                         "{{ (__controller_schedule_item.related.labels | map(attribute='name') | list if __controller_schedule_item.related.labels is defined else '') | default(__controller_schedule_item.labels) | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=[], omit_value=omit), true) }}"
    timeout:                        "{{ __controller_schedule_item.timeout | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=0, omit_value=omit), true) }}"
    job_type:                       "{{ __controller_schedule_item.job_type | default(omit, true) }}"
    job_tags:                       "{{ __controller_schedule_item.job_tags | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    skip_tags:                      "{{ __controller_schedule_item.skip_tags | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    limit:                          "{{ __controller_schedule_item.limit | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    diff_mode:                      "{{ __controller_schedule_item.diff_mode | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=false, omit_value=omit)) }}"
    verbosity:                      "{{ __controller_schedule_item.verbosity | default(omit, true) }}"
    organization:                   "{{ __controller_schedule_item.organization | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value='', omit_value=omit), true) }}"
    unified_job_template:           "{{ __controller_schedule_item.unified_job_template | default(omit, true) }}"
    enabled:                        "{{ __controller_schedule_item.enabled | default(lookup('infra.controller_configuration.enforce_defaults', enforce_default=controller_configuration_schedules_enforce_defaults , default_value=true, omit_value=omit)) }}"
    state:                          "{{ __controller_schedule_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_schedules | default( schedules ) }}"
  loop_control:
    loop_var: "__controller_schedule_item"
  no_log: "{{ controller_configuration_schedules_secure_logging }}"
  async: 1000
  poll: 0
  register: __controller_schedule_job_async
  changed_when: not __controller_schedule_job_async.changed
  vars:
    ansible_async_dir: '/tmp/.ansible_async'

- name: "Configure Schedules | Wait for finish the Schedules creation"
  ansible.builtin.async_status:
    jid: "{{ __controller_schedule_job_async_results_item.ansible_job_id }}"
  register: __controller_schedule_job_async_result
  until: __controller_schedule_job_async_result.finished
  retries: "{{ controller_configuration_schedules_async_retries }}"
  delay: "{{ controller_configuration_schedules_async_delay }}"
  loop: "{{ __controller_schedule_job_async.results }}"
  loop_control:
    loop_var: __controller_schedule_job_async_results_item
  when: __controller_schedule_job_async_results_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_schedules_secure_logging }}"
  vars:
    ansible_async_dir: '/tmp/.ansible_async'
...
