---
galaxy_info:
  role_name: "settings"
  author: "Sean Sullivan"
  description: A role to set some Ansible Automation gateway settings
  company: Red Hat

  license: "GPLv3"

  min_ansible_version: "2.14"

  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "gateway"
    - "aap"
    - "configuration"
    - "setting"
    - "settings"


dependencies: []
...
