---
- name: Get list of organizations from Tower
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ controller_password }}"
    return_content: true
    url: "https://{{ controller_hostname }}/api/v2/organizations/"
    user: "{{ controller_username }}"
    validate_certs: "{{ controller_validate_certs }}"
  register: existing_organizations

- name: Set fact when organization is present
  set_fact:
    org_exists: true
  when: org_names.name == which_org
  loop: "{{ existing_organizations.json.results }}"
  loop_control:
    loop_var: org_names

- name: Include organizations vars
  include_vars: ../vars/controller_organizations.yml
  when:
    - org_exists is not defined

- name: Include organizations vars
  include_vars: ../vars/controller_organizations_with_hub.yml
  when:
    - org_exists is defined
    - org_exists

- include_role:
    name: redhat_cop.controller_configuration.organizations
...
