---
tower_hostname: ""
tower_username: ""
tower_password: "" #Put in a vault at vars/tower-secrets.yml when tower_secrets: true
tower_oauthtoken: ""
validate_certs: false
tower_genie_rbac_secure_logging: "{{tower_genie_secure_logging | default(false)}}"

tower_rbac:
  - user: jdoe
    target_team: "My Team"
    role: member
  - team: "My Team"
    organization: "Default"
    role: execute
  - job_template: Demo Job Template
    organization: "Default"
    user: "admin"
    role: auditor
