---
# defaults file for filetree_create

#  Authentication variables
controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
controller_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"

# Controller object lists
controller_credentials: []
controller_execution_environments: []
controller_hosts: []
controller_inventories: []
controller_inventory_sources: []
controller_job_templates: []
controller_organizations: []
controller_projects: []
controller_roles: []
controller_schedules: []
controller_settings: []
controller_teams: []
controller_user_accounts: []
controller_workflow_job_templates: []

# Output directory path
output_path: "/tmp/filetree_output"

# Maximum number of objects to return from the list. If a list view returns more an max_objects an exception will be raised
query_controller_api_max_objects: 10000
...
