---
# defaults file for filetree_create

# Controller object lists
controller_credentials: []
controller_execution_environments: []
controller_hosts: []
controller_inventories: []
controller_inventory_sources: []
controller_job_templates: []
controller_organizations: []
controller_projects: []
controller_roles: []
controller_schedules: []
controller_settings: []
controller_teams: []
controller_user_accounts: []
controller_workflows: []

# Output directory path
output_path: "/tmp/filetree_output"

# Maximum number of objects to return from the list. If a list view returns more an max_objects an exception will be raised
query_controller_api_max_objects: 10000

controller_configuration_filetree_create_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"

input_tag:
  - all

...
