---

# These are the default variables common to most gateway_configuration roles
# You shouldn't need to define them again and again but they should be defined
# gateway_hostname: "{{ inventory_hostname }}"
# gateway_token: ""
# gateway_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the organizations
organizations_list: []
organizations_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
organizations_async_retries: "{{ aap_configuration_async_retries | default(30) }}"
organizations_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
organizations_enforce_defaults: "{{ aap_configuration_enforce_defaults | default(false) }}"
...
