---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.26.1
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v5.0.12
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -c .github/workflow-config/.ansiblelint.yml
          --exclude=roles/master_role_example
          --exclude=.github/workflows/
          --exclude=changelogs/
...
