---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.26.3
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v5.3.2
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -c .github/workflow-config/.ansiblelint.yml
          --exclude=roles/master_role_example
          --exclude=.github/workflows/
          --exclude=changelogs/
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: black
        entry: black
        args: [--config=.github/workflow-config/black.cfg, --check, --diff]
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [--config=.github/workflow-config/flake8.cfg]
        types: [python]
...
