---
- name: Organizations | Configuration # noqa fqcn[action-core]
  ansible.platform.organization:
    name: "{{ __gateway_organization_item.name | mandatory }}"
    new_name: "{{ __gateway_organization_item.new_name | default(omit) }}"
    description: "{{ __gateway_organization_item.description | default(omit) }}"
    state: "{{ __gateway_organization_item.state | default(platform_state | default(omit, true)) }}"

    # Role Standard Options
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ aap_organizations }}"
  loop_control:
    loop_var: __gateway_organization_item
    label: "{{ __operation.verb }} AAP Platform Organizations {{ __gateway_organization_item.name }}"
    pause: "{{ gateway_organizations_loop_delay }}"
  no_log: "{{ gateway_organizations_secure_logging }}"
  async: 1000
  poll: 0
  register: __gateway_organizations_job_async
  changed_when: not __gateway_organizations_job_async.changed
  vars:
    __operation: "{{ operation_translate[__gateway_organization_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"

- name: Organizations | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_organizations_job_async_results_item.ansible_job_id }}"
  register: __gateway_organizations_job_async_result
  until: __gateway_organizations_job_async_result.finished
  retries: "{{ gateway_organizations_async_retries }}"
  delay: "{{ gateway_organizations_async_delay }}"
  loop: "{{ __gateway_organizations_job_async.results }}"
  loop_control:
    loop_var: __gateway_organizations_job_async_results_item
    label: "{{ __operation.verb }} AAP Platform Organizations {{ __gateway_organizations_job_async_result.__gateway_organizations_job_async_results_item.__gateway_organization_item.name }} | Wait for finish the Organizations {{ __operation.action }}"
  when: __gateway_organizations_job_async_results_item.ansible_job_id is defined
  no_log: "{{ gateway_organizations_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__gateway_organizations_job_async_results_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
...
