---
argument_specs:
  main:
    short_description: An Ansible Role to create role user assignment on automation platform gateway.
    options:
      gateway_role_user_assignments:
        description: Data structure describing your role user assignment
        type: list
        required: true
        elements: dict
        options:
          role_definition:
            description:
              - The name or id of the role definition to assign to the user.
            required: true
            type: str
          object_id:
            description:
              - Primary key of the object this assignment applies to.
            required: true
            type: int
          user:
            description:
              - The name or id of the user to assign to the object.
            required: false
            type: str
          object_ansible_id:
            description:
              - Resource id of the object this role applies to. Alternative to the object_id field.
            required: false
            type: str
          user_ansible_id:
            description:
              - Resource id of the user who will receive permissions from this assignment. Alternative to user field.
            required: false
            type: str
          state:
            default: "{{ platform_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      gateway_role_user_assignments_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_role_user_assignments_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      gateway_role_user_assignments_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
