---
# a list of dictionaries describing the gateway applications
aap_applications: []
gateway_applications_secure_logging: "{{ aap_configuration_secure_logging | default('false') }}"
gateway_applications_async_retries: "{{ aap_configuration_async_retries | default(30) }}"
gateway_applications_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
gateway_applications_enforce_defaults: "{{ aap_configuration_enforce_defaults | default(false) }}"
aap_applications_loop_delay: "{{ aap_configuration_loop_delay | default(0) }}"
aap_configuration_async_dir:
...
