---
# Add Group Roles
- name: Add Roles to Groups in Automation Hubs
  group_roles:
    groups:           "{{ __group_role.groups | default(omit) }}"
    role_list:        "{{ __group_role.role_list | default(omit) }}"
    state:            "{{ __group_role.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_host | default(ah_hostname) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
    request_timeout:  "{{ ah_request_timeout | default(omit) }}"
  loop: "{{ ah_group_roles }}"
  loop_control:
    loop_var: "__group_role"
  no_log: "{{ ah_configuration_group_roles_secure_logging }}"
  async: 1000
  poll: 0
  register: __group_roles_job_async
  changed_when: not __group_roles_job_async.changed
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'

- name: "Add Roles to Groups | Wait for finish the group creation"
  ansible.builtin.async_status:
    jid: "{{ __group_roles_job_async_result_item.ansible_job_id }}"
  register: __group_roles_job_async_result
  until: __group_roles_job_async_result.finished
  retries: "{{ ah_configuration_group_roles_async_retries }}"
  delay: "{{ ah_configuration_group_roles_async_delay }}"
  loop: "{{ __group_roles_job_async.results }}"
  loop_control:
    loop_var: __group_roles_job_async_result_item
  when: __group_roles_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_group_roles_secure_logging }}"
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'
...
