---
# Add Group Roles
- name: Add Roles to Groups in Automation Hubs
  ansible.hub.group_roles:
    groups:           "{{ __group_roles_item.groups | default(omit) }}"
    role_list:        "{{ __group_roles_item.role_list | default(omit) }}"
    state:            "{{ __group_roles_item.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ aap_hostname | default(omit) }}"
    ah_username:     "{{ aap_username | default(omit) }}"
    ah_password:      "{{ aap_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ aap_validate_certs | default(omit) }}"
    request_timeout:  "{{ aap_request_timeout | default(omit) }}"
  loop: "{{ ah_group_roles }}"
  loop_control:
    loop_var: __group_roles_item
    label: "{{ __operation.verb }} the group role {{ __ah_configuration_group_roles__item.name }} in Hub"
    pause: "{{ ah_configuration_group_roles_loop_delay }}"
  no_log: "{{ ah_configuration_group_roles_secure_logging }}"
  async: "{{ ah_configuration_group_roles_async_timeout }}"
  poll: 0
  register: __group_roles_job_async
  changed_when: not __group_roles_job_async.changed
  vars:
    __operation: "{{ operation_translate[__group_roles_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: '{{ aap_configuration_async_dir }}'

- name: "Add Roles to Groups | Wait for finish the group creation"
  ansible.builtin.async_status:
    jid: "{{ __group_roles_job_async_result_item.ansible_job_id }}"
  register: __group_roles_job_async_result
  until: __group_roles_job_async_result.finished
  retries: "{{ ah_configuration_group_roles_async_retries }}"
  delay: "{{ ah_configuration_group_roles_async_delay }}"
  loop: "{{ __group_roles_job_async.results }}"
  loop_control:
    loop_var: __group_roles_job_async_result_item
    label: "{{ __operation.verb }} Label {{ __group_roles_job_async_result_item.__group_roles_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __group_roles_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_group_roles_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__group_roles_job_async_result_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: '{{ aap_configuration_async_dir }}'
...
