---
- name: Playbook to configure ansible tower post installation
  hosts: localhost
  connection: local
  # Define following vars here, or in tower_configs/tower_auth.yml
  # tower_hostname: ansible-tower-web-svc-test-project.example.com
  # tower_username: admin
  # tower_password: changeme
  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs
        ignore_files: [tower_config.yml.template]
        extensions: ["yml"]
      tags:
        - always
  roles:
    - {role: tower_settings, when: tower_settings is defined, tags: tower_settings}
    - {role: organizations, when: tower_organizations is defined, tags: organizations}
    - {role: users, when: tower_user_accounts is defined, tags: users}
    - {role: teams, when: tower_teams is defined, tags: teams}
    - {role: credentials, when: tower_credentials is defined, tags: credentials}
    - {role: credential_input_sources, when: tower_credential_input_sources is defined, tags: credential_input_sources}
    - {role: inventories, when: tower_inventories is defined, tags: inventories}
    - {role: projects, when: tower_projects is defined, tags: projects}
    - {role: inventory_sources, when: tower_inventory_sources is defined, tags: inventory_sources}
    - {role: groups, when: tower_groups is defined, tags: inventories}
    - {role: hosts, when: tower_hosts is defined, tags: hosts}
    - {role: job_templates, when: tower_templates is defined, tags: job_templates}
    - {role: workflow_job_templates, when: workflow_job_templates is defined, tags: workflow_job_templates}
    - {role: schedules, when: tower_schedules is defined, tags: schedules}
    - {role: notifications, when: tower_notifications is defined, tags: notifications}
    - {role: tower_role, when: tower_rbac is defined, tags: tower_role}
