---
eda_rulebook_activations: []

eda_configuration_rulebook_activation_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
eda_configuration_rulebook_activation_async_retries: "{{ aap_configuration_async_retries | default(50) }}"
eda_configuration_rulebook_activation_async_delay: "{{ aap_configuration_async_delay| default(1) }}"
aap_configuration_async_dir: null
...
