---
automation_hub_list:
  - name: automation_hub
    url: "{{ ah_hostname }}"
    auth_url: "{{ ah_hostname }}api/automation-hub/"  # {{ah_hostname}}api/galaxy/ for AH {{ah_hostname}}api/automation-hub/ for Galaxy
    username: "{{ ah_username }}"
    password: "{{ ah_password }}"

ansible_config_list:
  - header: galaxy
    keypairs:
      - key: ignore_certs
        value: "{% if validate_certs %}false{% else %}true{% endif %}"
      - key: server_list
        value: "automation_hub"

ah_configuration_working_dir: "test"
...
