---
ah_namespaces:
  - name: community_test
    company: Community Test
    email: user@example.com
    avatar_url: https://github.com/ansible/awx-logos/blob/master/awx/ui/client/assets/logo-header.svg
    description: string
    resources: "# Community\nA Namespace test with changes"
    links:
      - name: "Nothing"
        url: "https://github.com/ansible/awx"
    groups:
      - name: system:partner-engineers  # Galaxy: system:partner-engineers AH: admins
        object_permissions:
          - "change_namespace"
          - "upload_to_namespace"
...
