---
- name: Service Keys | Configuration # noqa fqcn[action-core]
  ansible.platform.service_key:
    name: "{{ __gateway_service_keys_item.name | mandatory }}"
    new_name: "{{ __gateway_service_keys_item.new_name | default(omit) }}"
    is_active: "{{ __gateway_service_keys_item.is_active | default(omit) }}"
    service_cluster: "{{ __gateway_service_keys_item.service_cluster | default(omit) }}"
    algorithm: "{{ __gateway_service_keys_item.algorithm | default(omit) }}"
    secret: "{{ __gateway_service_keys_item.secret | default(omit) }}"
    secret_length: "{{ __gateway_service_keys_item.secret_length | default(omit) }}"
    mark_previous_inactive: "{{ __gateway_service_keys_item.mark_previous_inactive | default(omit) }}"
    state: "{{ __gateway_service_keys_item.state | default(platform_state | default(omit, true)) }}"

    # Role Standard Options
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ gateway_service_keys }}"
  loop_control:
    loop_var: __gateway_service_keys_item
    label: "{{ __operation.verb }} the Gateway service key {{ __gateway_service_keys_item.name }}"
    pause: "{{ gateway_service_keys_loop_delay }}"
  no_log: "{{ gateway_service_keys_secure_logging }}"
  async: 1000
  poll: 0
  register: __gateway_service_keys_job_async
  changed_when: not __gateway_service_keys_job_async.changed
  vars:
    __operation: "{{ operation_translate[__gateway_service_keys_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"

- name: Service Keys | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_service_keys_job_async_results_item.ansible_job_id }}"
  register: __gateway_service_keys_job_async_result
  until: __gateway_service_keys_job_async_result.finished
  retries: "{{ gateway_service_keys_async_retries }}"
  delay: "{{ gateway_service_keys_async_delay }}"
  loop: "{{ __gateway_service_keys_job_async.results }}"
  loop_control:
    loop_var: __gateway_service_keys_job_async_results_item
    label: "{{ __operation.verb }} Label {{ __gateway_service_keys_job_async_results_item.__gateway_service_keys_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __gateway_service_keys_job_async_results_item.ansible_job_id is defined
  no_log: "{{ gateway_service_keys_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__gateway_service_keys_job_async_results_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
...
