---
controller_configuration_project_update_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
controller_configuration_project_update_async_retries: "{{ controller_configuration_async_retries | default(60) }}"
controller_configuration_project_update_async_delay: "{{ controller_configuration_async_delay | default(10) }}"
controller_configuration_project_update_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
controller_configuration_async_dir: null
...
