---
# list of dicts to describe Controller inventories
controller_inventories: []
controller_configuration_inventories_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
controller_configuration_inventories_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_inventories_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
controller_configuration_inventories_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
controller_configuration_async_dir: null
controller_configuration_inventories_enforce_defaults: "{{ controller_configuration_enforce_defaults | default(false) }}"
...
