---

# Create AH Role
- name: Add Automation Hub role
  ansible.hub.ah_role:
    name:             "{{ __role_item.name }}"
    description:      "{{ __role_item.description | default(omit) }}"
    perms:            "{{ __role_item.perms | default(omit) }}"
    state:            "{{ __role_item.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ aap_hostname | default(omit) }}"
    ah_username:     "{{ aap_username | default(omit) }}"
    ah_password:      "{{ aap_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ aap_validate_certs | default(omit) }}"
    request_timeout:  "{{ aap_request_timeout | default(omit) }}"
  loop: "{{ ah_roles }}"
  loop_control:
    loop_var: __role_item
    label: "{{ __operation.verb }} the role {{ __ah_configuration_role__item.name }} to Hub"
    pause: "{{ ah_configuration_role_loop_delay }}"
  no_log: "{{ ah_configuration_role_secure_logging }}"
  async: "{{ ah_configuration_role_async_timeout }}"
  poll: 0
  register: __roles_job_async
  changed_when: not __roles_job_async.changed
  vars:
    __operation: "{{ operation_translate[__role_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: '{{ aap_configuration_async_dir }}'

- name: "Create Role | Wait for finish the role creation"
  ansible.builtin.async_status:
    jid: "{{ __roles_job_async_result_item.ansible_job_id }}"
  register: __roles_job_async_result
  until: __roles_job_async_result.finished
  retries: "{{ ah_configuration_role_async_retries }}"
  delay: "{{ ah_configuration_role_async_delay }}"
  loop: "{{ __roles_job_async.results }}"
  loop_control:
    loop_var: __roles_job_async_result_item
    label: "{{ __operation.verb }} Label {{ __roles_job_async_result_item.__role_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __roles_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_role_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__roles_job_async_result_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: '{{ aap_configuration_async_dir }}'
...
