---

# Launch tower Workflow
- name: Launch a Tower Workflow
  tower_workflow_launch:
    name:                     "{{ __workflow_launch_item.name }}"
    organization:             "{{ __workflow_launch_item.organization | default(omit) }}"
    inventory:                "{{ __workflow_launch_item.inventory | default(omit) }}"
    limit:                    "{{ __workflow_launch_item.limit | default(omit) }}"
    scm_branch:               "{{ __workflow_launch_item.scm_branch | default(omit) }}"
    extra_vars:               "{{ __workflow_launch_item.extra_vars | default(omit) }}"
    wait:                     "{{ __workflow_launch_item.wait | default(omit) }}"
    interval:                 "{{ __workflow_launch_item.interval | default(omit) }}"
    timeout:                  "{{ __workflow_launch_item.timeout | default(omit) }}"

    # Role Standard Options
    tower_username:     "{{ tower_username | default(omit) }}"
    tower_password:     "{{ tower_password | default(omit) }}"
    tower_oauthtoken:   "{{ tower_oauthtoken | default(omit) }}"
    tower_host:         "{{ tower_hostname }}"
    tower_config_file:  "{{ tower_config_file | default(omit) }}"
    validate_certs:     "{{ tower_validate_certs | default('true') }}"
  loop: "{{ tower_workflow_launch_jobs }}"
  loop_control:
    loop_var: "__workflow_launch_item"
  no_log: "{{ tower_configuration_workflow_launch_secure_logging }}"
  register: launched_tower_workflows
  when: tower_workflow_launch_jobs is defined
