---
# vars file for filetree_create
valid_tags:
  - all
  - settings
  - credentials
  - credential_types
  - execution_environments
  - groups
  - hosts
  - inventory
  - inventory_sources
  - job_templates
  - notification_templates
  - organizations
  - projects
  - roles
  - teams
  - users
  - workflow_job_templates
  - instance_groups
  - applications
  - labels
  - schedules
...
