---

# Create EDA Controller user
- name: Add EDA Controller user
  ansible.eda.user:
    username:            "{{ __user_item.username }}"
    new_username:        "{{ __user_item.new_username | default(omit) }}"
    first_name:          "{{ __user_item.first_name | default(omit) }}"
    last_name:           "{{ __user_item.last_name | default(omit) }}"
    email:               "{{ __user_item.email | default(omit) }}"
    password:            "{{ __user_item.password | default(omit) }}"
    update_secrets:      "{{ __user_item.update_secrets | default(omit) }}"
    is_superuser:        "{{ __user_item.is_superuser | default(omit) }}"
    roles:               "{{ __user_item.roles | default(omit) }}"
    state:               "{{ __user_item.state | default(eda_state | default('present')) }}"
    controller_host:     "{{ eda_host | default(eda_hostname) }}"
    controller_username: "{{ eda_username | default(omit) }}"
    controller_password: "{{ eda_password | default(omit) }}"
    validate_certs:      "{{ eda_validate_certs | default(omit) }}"
    request_timeout:     "{{ eda_request_timeout | default(omit) }}"
  loop: "{{ eda_users }}"
  loop_control:
    loop_var: "__user_item"
  no_log: "{{ eda_configuration_user_secure_logging }}"
  async: 1000
  poll: 0
  register: __users_job_async
  changed_when: not __users_job_async.changed
  vars:
    ansible_async_dir: '{{ eda_configuration_async_dir }}'

- name: "Create user | Wait for finish the user creation"
  ansible.builtin.async_status:
    jid: "{{ __users_job_async_result_item.ansible_job_id }}"
  register: __users_job_async_result
  until: __users_job_async_result.finished
  retries: "{{ eda_configuration_user_async_retries }}"
  delay: "{{ eda_configuration_user_async_delay }}"
  loop: "{{ __users_job_async.results }}"
  loop_control:
    loop_var: __users_job_async_result_item
  when: __users_job_async_result_item.ansible_job_id is defined
  no_log: "{{ eda_configuration_user_secure_logging }}"
  vars:
    ansible_async_dir: '{{ eda_configuration_async_dir }}'
...
