---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_hostname: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# ah_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the Automation Hub execution environment image
ah_ee_images: []
# possible fields:
#  - name: name: ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0-15
#    state: present
#    append: true
#    tags:
#      - v2
#      - "2.0"
#      - prod1

ah_configuration_ee_image_secure_logging: "{{ ah_configuration_secure_logging | default(false) }}"
ah_configuration_ee_image_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
ah_configuration_ee_image_async_delay: "{{ ah_configuration_async_delay | default(1) }}"
...
