---
argument_specs:
  main:
    short_description: An Ansible Role to create authenticator maps on automation platform gateway.
    options:
      gateway_authenticator_maps:
        description: Data structure describing your authenticator maps
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: The name of the authenticator mapping, must be unique
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          authenticator:
            type: str
            required: true
            description: The name of ID referencing the Authenticator
          new_authenticator:
            type: str
            description: Setting this option will change the existing authenticator (looked up via the authenticator field)
          revoke:
            type: bool
            description: If a user does not meet this rule should we revoke the permission
          map_type:
            type: str
            description: |
              What does the map work on, a team, a user flag or is this an allow rule
              Defaults to "team" (by API)
            choices: [allow, is_superuser, team, organization, role]
          team:
            type: str
            description: |
              A team name this rule works on
              required if map_type is a 'team'
              required if role's content type is a 'team'
          organization:
            type: str
            description: |
              An organization name this rule works on
              required if map_type is either 'organization' or 'team'
              required if role's content type is either 'organization' or 'team'
          role:
            type: str
            description: The name of the RBAC Role Definition to be used for this map
          triggers:
            type: dict
            description: Trigger information for this rule
          order:
            type: int
            description: |
              The order in which this rule should be processed, smaller numbers are of higher precedence
              Items with the same order will be executed in random order
              Value must be greater or equal to 0
          state:
            default: "{{ platform_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      gateway_authenticator_maps_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_authenticator_maps_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      gateway_authenticator_maps_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
