---

# Create AH Role
- name: Add Automation Hub role
  ah_role:
    name:             "{{ __role.name }}"
    description:      "{{ __role.description | default(omit) }}"
    perms:            "{{ __role.perms | default(omit) }}"
    state:            "{{ __role.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_host | default(ah_hostname) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
    request_timeout:  "{{ ah_request_timeout | default(omit) }}"
  loop: "{{ ah_roles }}"
  loop_control:
    loop_var: "__role"
  no_log: "{{ ah_configuration_role_secure_logging }}"
  async: 1000
  poll: 0
  register: __roles_job_async
  changed_when: not __roles_job_async.changed
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'

- name: "Create Role | Wait for finish the role creation"
  ansible.builtin.async_status:
    jid: "{{ __roles_job_async_result_item.ansible_job_id }}"
  register: __roles_job_async_result
  until: __roles_job_async_result.finished
  retries: "{{ ah_configuration_role_async_retries }}"
  delay: "{{ ah_configuration_role_async_delay }}"
  loop: "{{ __roles_job_async.results }}"
  loop_control:
    loop_var: __roles_job_async_result_item
  when: __roles_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_role_secure_logging }}"
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'
...
