---
galaxy_info:
  role_name: "ansible_tower_genie_inventories"
  author: "Andrew J. Huffman, Kedar Kulkarni"
  description: "An Ansible role to create inventories and inventory sources."
  company: "Red Hat"

  license: "MIT"

  min_ansible_version: "2.4"

  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "ansibletower"
    - "tower"
    - "awx"
    - "genie"
    - "inventory"
    - "inventories"
    - "source"
