---

# Create AH Group
- name: Add Automation Hub group
  ansible.hub.ah_group:
    name:             "{{ __group.name | default(omit) }}"
    # new_name:         "{{ __group.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
    state:            "{{ __group.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ aap_hostname | default(omit) }}"
    ah_username:     "{{ aap_username | default(omit) }}"
    ah_password:      "{{ aap_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ aap_validate_certs | default(omit) }}"
    request_timeout:  "{{ aap_request_timeout | default(omit) }}"
  loop: "{{ aap_teams }}"
  loop_control:
    loop_var: "__group"
    label: "{{ __operation.verb }} the label {{ __ah_configuration_group__item.name }} to Controller"
    pause: "{{ ah_configuration_group__loop_delay }}"
  no_log: "{{ ah_configuration_group_secure_logging }}"
  async: "{{ ah_configuration_group_async_timeout }}"
  poll: 0
  register: __groups_job_async
  changed_when: not __groups_job_async.changed
  vars:
    ansible_async_dir: '{{ aap_configuration_async_dir }}'

- name: "Create Group | Wait for finish the group creation"
  ansible.builtin.async_status:
    jid: "{{ __groups_job_async_result_item.ansible_job_id }}"
  register: __groups_job_async_result
  until: __groups_job_async_result.finished
  retries: "{{ ah_configuration_group_async_retries }}"
  delay: "{{ ah_configuration_group_async_delay }}"
  loop: "{{ __groups_job_async.results }}"
  loop_control:
    loop_var: __groups_job_async_result_item
    label: "{{ __operation.verb }} Label {{ __groups_job_async_result_item.__group_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __groups_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_group_secure_logging }}"
  vars:
    ansible_async_dir: '{{ aap_configuration_async_dir }}'
...
