---
tower_url: ""
tower_user: ""
tower_pass: "" #Put in a vault at vars/tower-secrets.yml when tower_secrets: True
tower_org: ""
tower_verify_ssl: False
tower_team_name: ""
tower_team_desc: ""
tower_secrets: False
