---
- name: "Managing Credential Types"
  credential_type:
    name:                           "{{ __controller_credential_type_item.name | mandatory }}"
    new_name:                       "{{ __controller_credential_type_item.new_name | default(omit, true) }}"
    description:                    "{{ __controller_credential_type_item.description | default(('' if controller_configuration_credential_types_enforce_defaults else omit), true) }}"
    injectors:                      "{{ __controller_credential_type_item.injectors | default(({} if controller_configuration_credential_types_enforce_defaults else omit), true) | regex_replace('[ ]{2,}', '') }}"
    inputs:                         "{{ __controller_credential_type_item.inputs | default(({} if controller_configuration_credential_types_enforce_defaults else omit), true) }}"
    kind:                           "{{ __controller_credential_type_item.kind | default('cloud') }}"
    state:                          "{{ __controller_credential_type_item.state | default(controller_state | default('present')) }}"

    # Role specific options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    request_timeout:                "{{ controller_request_timeout | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ credential_types if credential_types is defined else controller_credential_types }}"
  loop_control:
    loop_var: __controller_credential_type_item
    label: "{{ __operation.verb }} Credential Type {{ __controller_credential_type_item.name }}"
    pause: "{{ controller_configuration_credential_types_loop_delay }}"
  no_log: "{{ controller_configuration_credential_types_secure_logging }}"
  async: "{{ ansible_check_mode | ternary(0, 1000) }}"
  poll: 0
  register: __credentialtypes_job_async
  changed_when: "(__credentialtypes_job_async.changed if ansible_check_mode else false)"
  vars:
    __operation: "{{ operation_translate[__controller_credential_type_item.state | default(controller_state) | default('present')] }}"
    ansible_async_dir: '{{ controller_configuration_async_dir }}'

- name: "Flag for errors (check mode only)"
  ansible.builtin.set_fact:
    error_flag: true
  when: ansible_check_mode and __credentialtypes_job_async.failed is defined and __credentialtypes_job_async.failed

- name: "Managing Controller Credential Types | Wait for finish the credential types management"
  ansible.builtin.async_status:
    jid: "{{ __credentialtypes_job_async_result_item.ansible_job_id }}"
  register: __credentialtypes_job_async_result
  until: __credentialtypes_job_async_result.finished
  retries: "{{ controller_configuration_credential_types_async_retries }}"
  delay: "{{ controller_configuration_credential_types_async_delay }}"
  loop: "{{ __credentialtypes_job_async.results }}"
  loop_control:
    loop_var: __credentialtypes_job_async_result_item
    label: "{{ __operation.verb }} Controller Credential Type {{ __credentialtypes_job_async_result_item }} | Wait for finish the credential type {{ __operation.action }}"
  when: not ansible_check_mode and __credentialtypes_job_async_result_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_credential_types_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__credentialtypes_job_async_result_item.__controller_credential_type_item.state | default(controller_state) | default('present')] }}"
    ansible_async_dir: '{{ controller_configuration_async_dir }}'
...
