---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_username: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# aap_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the Automation Hub ee repository
ah_ee_registries: []
# possible fields:
#  - name: "registry" # mandatory
#    url: registry.redhat.io # mandatory
#    username: myuser
#    password: mypass
#    tls_validation: false
#    proxy_url: myproxy.example.com:8080
#    proxy_username: proxyadmin
#    proxy_password: proxyadmin
#    download_concurrency: 100
#    rate_limit: 5
#    state: present

ah_configuration_ee_registry_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
ah_configuration_ee_registry_async_timeout: "{{ aap_configuration_async_timeout | default(1000) }}"
ah_configuration_ee_registry_async_retries: "{{ aap_configuration_async_retries | default(50) }}"
ah_configuration_ee_registry_loop_delay: "{{ aap_configuration_loop_delay | default(0) }}"
ah_configuration_ee_registry_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
aap_configuration_async_dir: null
...
