---
galaxy_info:
<<<<<<< HEAD
  role_name: "organizations"
  author: "Sean Sulivan"
  description: "An Ansible Role to create Organizations in Ansible Controller."
  company: "Red Hat"
=======
  role_name: organizations
  author: Martin Slemr
  description: An Ansible Role to create organizations in Automation Platform Gateway.
  company: Red Hat
>>>>>>> 40b40ddac1c00aac7d878bd41af23a6d562296e5

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
<<<<<<< HEAD
  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  # github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "controller"
    - "aap"
    - "awx"
    - "configuration"
    - "organization"
    - "organizations"

collections:
  - ansible.controller
  - awx.awx

dependencies:
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  - role: global_vars
  - role: meta_dependency_check
=======
  license: GPLv3

  min_ansible_version: 2.16.0

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - gateway
    - aap
    - configuration
    - organization
    - organizations

dependencies: []
>>>>>>> 40b40ddac1c00aac7d878bd41af23a6d562296e5
...
