---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false

# These are the default variables specific to the license role

# a list of dicts describing Controller credentials
controller_credentials: []
# possible fields
# - name: "cred_name" 
#  new_name: "new_name"  
#  description: "some description"  
#  organization: "Default"  
#  credential_type: "ssh"  
#  kind:  
#  inputs: {}  
#  user: "owner_name"  
#  team: "owner_name"
#  state: present 

controller_configuration_credentials_secure_logging: "{{ controller_configuration_secure_logging | default(true) }}"
controller_configuration_credentials_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_credentials_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
