---
# Playbook to install Ansible Tower as a single node

- name: Install Ansible Tower on OCP
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    tower_release_version: latest
  roles:
    - sean_m_sullivan.tower_utilities.install_ocp
