---
controller_settings:
  # - name: ACTIVITY_STREAM_ENABLED
  #   value: true
  # - name: ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC
  #   value: false
  # - name: SESSION_COOKIE_AGE
  #   value: 1800
  # - name: SESSIONS_PER_USER
  #   value: 10
  # - name: MANAGE_ORGANIZATION_AUTH
  #   value: true
  #   https://access.redhat.com/solutions/6613291 -  External users are not able to create token on Ansible Tower.
  - name: ALLOW_OAUTH2_FOR_EXTERNAL_USERS
    value: true
  - name: ORG_ADMINS_CAN_SEE_ALL_USERS
    value: false
...
