---
controller_settings:
  - name: AUTH_LDAP_SERVER_URI
    value: "ldap://idm.automationiberia.com"
  - name: AUTH_LDAP_BIND_DN
    value: "{{ vault_ldap_bind_dn | default('uid=controller-binddn,cn=sysaccounts,cn=etc,dc=automationiberia,dc=com') }}"
  - name: AUTH_LDAP_BIND_PASSWORD
    value: "{{ vault_ldap_bind_password | default('password') }}"
  - name: AUTH_LDAP_START_TLS
    value: false
  - name: AUTH_LDAP_USER_DN_TEMPLATE
    value: ""
  - name: AUTH_LDAP_CONNECTION_OPTIONS
    value:
      OPT_REFERRALS: 0
      OPT_NETWORK_TIMEOUT: 30
  - name: AUTH_LDAP_USER_SEARCH
    value: ["cn=users,cn=accounts,dc=bcnconsulting,dc=com", "SCOPE_SUBTREE", "(uid=%(user)s)"]
  - name: AUTH_LDAP_USER_DN_TEMPLATE
    value: ""
  - name: AUTH_LDAP_USER_ATTR_MAP
    value: {"first_name": "givenName", "last_name": "sn", "email": "mail"}
  - name: AUTH_LDAP_GROUP_SEARCH
    value: ["cn=groups,cn=accounts,dc=bcnconsulting,dc=com", "SCOPE_SUBTREE", "(objectClass=posixgroup)"]
  - name: AUTH_LDAP_GROUP_TYPE
    value: "MemberDNGroupType"
  - name: AUTH_LDAP_GROUP_TYPE_PARAMS
    value: {"name_attr": "cn", "member_attr": "member"}
  - name: AUTH_LDAP_REQUIRE_GROUP
    value: ""
  - name: AUTH_LDAP_DENY_GROUP
    value: ""
  - name: AUTH_LDAP_USER_FLAGS_BY_GROUP
    value: {"is_superuser": ["cn=controller-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"], "is_system_auditor": ["cn=team-ldap-auditor,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"]}
  - name: AUTH_LDAP_ORGANIZATION_MAP
    value: {
      "{{ orgs }}": {
        "admins": "cn=controller-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove_users": true,
        "remove_admins": true
      },
      "Organization1": {
        "admins": [
          "cn=team-ldap-org01-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"
        ],
        "users": [
          "cn=team-ldap-org01-users,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
          "cn=team-ldap-org01-devs,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"
        ],
        "remove_users": true,
        "remove_admins": true
      },
      "Organization2": {
        "admins": [
          "cn=team-ldap-org02-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"
        ],
        "users": [
          "cn=team-ldap-org02-users,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
          "cn=team-ldap-org02-devs,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"
        ],
        "remove_users": true,
        "remove_admins": true
      }
    }
  - name: AUTH_LDAP_TEAM_MAP
    value: {
      "ldap-controller-admins": {
        "organization": "{{ orgs }}",
        "users": "cn=team-ldap-controller-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-users-cmdb": {
        "organization": "{{ orgs }}",
        "users": "cn=team-ldap-cmdb-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-users-crossteam": {
        "organization": "CrossTeamOrg",
        "users": "cn=team-ldap-users-crossteam,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org01-admins": {
        "organization": "Organization1",
        "users": "cn=team-ldap-org01-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org01-users": {
        "organization": "Organization1",
        "users": "cn=team-ldap-org01-users,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org01-devs": {
        "organization": "Organization1",
        "users": "cn=team-ldap-org01-devs,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org02-admins": {
        "organization": "Organization2",
        "users": "cn=team-ldap-org02-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org02-users": {
        "organization": "Organization2",
        "users": "cn=team-ldap-org02-users,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      },
      "ldap-org02-devs": {
        "organization": "Organization2",
        "users": "cn=team-ldap-org02-devs,cn=groups,cn=accounts,dc=bcnconsulting,dc=com",
        "remove": true
      }
    }
...
