---
- name: "Get current Credential Types from the API when AAP"
  set_fact:
    credential_types_lookvar: "{{ query(controller_api_plugin, 'api/v2/credential_types/',
                                        query_params={ 'managed': false },
                                        host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs,
                                        return_all=true, max_objects=query_controller_api_max_objects)
                               }}"
  when: is_aap

- name: "Get current Credential Types from the API when Tower"
  set_fact:
    credential_types_lookvar: "{{ query(controller_api_plugin, 'api/v2/credential_types/', query_params={ 'managed_by_tower': false }, host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs, return_all=true, max_objects=query_controller_api_max_objects) }}"
  when: not is_aap

- name: "Create the output directory for credential types: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current credential types to the output yaml file: {{ output_path }}/current_credential_types.yaml"
  template:
    src: "templates/current_credential_types.j2"
    dest: "{{ output_path }}/current_credential_types.yaml"
    mode: '0644'
  vars:
    current_credential_types_asset_value: "{{ credential_types_lookvar }}"
...
