---
# Create AH repository
- name: Sync Automation Hub Collection Remote repository
  collection_repository_sync:
    name:                     "{{ __collection_repository_sync_item.name }}"
    wait:                     "{{ __collection_repository_sync_item.wait | default(omit) }}"
    interval:                 "{{ __collection_repository_sync_item.interval | default(1) }}"
    timeout:                  "{{ __collection_repository_sync_item.timeout | default(omit) }}"
    ah_host:                  "{{ ah_host | default(ah_hostname) }}"
    ah_username:              "{{ ah_username | default(omit) }}"
    ah_password:              "{{ ah_password | default(omit) }}"
    ah_path_prefix:           "{{ ah_path_prefix | default(omit) }}"
    validate_certs:           "{{ ah_validate_certs | default(omit) }}"
    request_timeout:          "{{ ah_request_timeout | default(omit) }}"
  loop: "{{ ah_collection_repositories }}"
  loop_control:
    loop_var: "__collection_repository_sync_item"
  no_log: "{{ ah_configuration_collection_repository_sync_secure_logging }}"
  async: 1000
  poll: 0
  register: __collection_repository_sync_job_async
  changed_when: not __collection_repository_sync_job_async.changed
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'

- name: "Sync Repository | Wait for finish the repository sync"
  ansible.builtin.async_status:
    jid: "{{ __collection_repository_sync_job_async_result_item.ansible_job_id }}"
  register: __collection_repository_sync_job_async_result
  until: __collection_repository_sync_job_async_result.finished
  retries: "{{ ah_configuration_collection_repository_sync_async_retries }}"
  delay: "{{ ah_configuration_collection_repository_sync_async_delay }}"
  loop: "{{ __collection_repository_sync_job_async.results }}"
  loop_control:
    loop_var: __collection_repository_sync_job_async_result_item
  when: __collection_repository_sync_job_async_result_item.ansible_job_id is defined
  no_log: "{{ ah_configuration_collection_repository_sync_secure_logging }}"
  vars:
    ansible_async_dir: '{{ ah_configuration_async_dir }}'

...
