---

# These are the default variables common to most gateway_configuration roles
# You shouldn't need to define them again and again but they should be defined
# aap_hostname: "{{ inventory_hostname }}"
# gateway_token: ""
# aap_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the service nodes
service_nodes_list: []
service_nodes_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
service_nodes_async_retries: "{{ aap_configuration_async_retries | default(30) }}"
service_nodes_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
service_nodes_enforce_defaults: "{{ aap_configuration_enforce_defaults | default(false) }}"
...
