---
# a list of dictionaries describing the gateway applications
gateway_applications: []
gateway_configuration_applications_secure_logging: "{{ gateway_configuration_secure_logging | default('false') }}"
gateway_configuration_applications_async_retries: "{{ gateway_configuration_async_retries | default(30) }}"
gateway_configuration_applications_async_delay: "{{ gateway_configuration_async_delay | default(1) }}"
gateway_configuration_async_dir: null
gateway_configuration_applications_enforce_defaults: "{{ gateway_configuration_enforce_defaults | default(false) }}"
...
