---
# tasks file for gateway_settings
- name: Update automation platform gateway Settings
  ansible.platform.settings:
    settings: "{{ settings_list | default(omit, true) }}"

    # Role Standard Options
    gateway_hostname: "{{ platform_hostname | default(omit, true) }}"
    gateway_password: "{{ platform_password | default(omit, true) }}"
    gateway_username: "{{ platform_username | default(omit, true) }}"
    gateway_token: "{{ platform_token | default(omit, true) }}"
    gateway_request_timeout: "{{ platform_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ platform_validate_certs | default(omit) }}"
  no_log: "{{ settings_secure_logging }}"
  register: __gateway_setting_job
...
