---

- name: Find the current run time.
  set_fact:
    backup_date: '{{ lookup("pipe", "date +%F-%T") }}'

- name: Include Requirements
  include_tasks: requirements.yml
  when: requirements

- name: Include Online Virtualenv
  include_tasks: online.yml
  when: virtual_online

- name: Include Offline Virtualenv
  include_tasks: offline.yml
  when: virtual_offline

- name: Include Backup of the Virtualenv
  include_tasks: online.yml
  when: virtual_backup
