---
# tasks file for controller_credential_types
- name: "OBJECT DIFF: Get the API list of all Credential Types"
  ansible.builtin.set_fact:
    __controller_api_credential_types: "{{ query(controller_api_plugin, 'credential_types',
      query_params={'managed': false},
      host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) }}"      

- name: "OBJECT DIFF: Find the difference of Credential Types between what is on the Controller versus CasC on SCM"
  ansible.builtin.set_fact:
    __credential_types_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
      api_list=__controller_api_credential_types, compare_list=controller_credential_types,
      with_present=false, set_absent=true) }}"

- name: "OBJECT DIFF: Set credential's list to be configured"
  ansible.builtin.set_fact:
    controller_credential_types: "{{ __credential_types_difference }}"
...
