---
- name: Get the organization ID
  ansible.builtin.set_fact:
    controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                            query_params={'name': orgs},
                                            host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=false)
                                 }}"

- name: "OBJECT DIFF: Get the API list of all inventories"
  ansible.builtin.set_fact:
    __controller_api_inventories: "{{ query(controller_api_plugin, 'inventories',
                                            query_params={'organization': controller_organization_id.id,
                                              'has_inventory_sources': 'false',
                                              'not__total_groups': '0',
                                              'not__kind': 'smart'},
                                            host=controller_hostname, username=controller_username,
                                            password=controller_password, verify_ssl=false)
                                   }}"

- name: "OBJECT DIFF: Get the API list of all groups in the inventories at organization {{ orgs }}"
  ansible.builtin.set_fact:
    __controller_api_groups: "{{ (__controller_api_groups | default([])) + query(controller_api_plugin, 'groups',
                                          query_params={'inventory': current_inventory.id},
                                          host=controller_hostname, username=controller_username,
                                          password=controller_password, verify_ssl=false)
                              }}"
  loop: "{{ __controller_api_inventories }}"
  loop_control:
    loop_var: current_inventory

- name: "Group differences (block)"
  block:
    - name: "OBJECT DIFF: Find the difference of Groups between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __groups_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                        query_params={'summary_fields.inventory.organization_id': controller_organization_id.id},
                                        api_list=__controller_api_groups, compare_list=controller_groups,
                                        with_present=false, set_absent=true)
                              }}"

    - name: "OBJECT DIFF: Set the inventory key at the correct place"
      ansible.builtin.set_fact:
        controller_groups: "{{ __groups_difference }}"

  when: __controller_api_groups is defined
...
