---
- name: "Get the current controller user to determine if it is super-admin"
  ansible.builtin.set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup(controller_api_plugin, 'me',
                                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                                   }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Role differences (block)"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
  block:
    - name: "Gets current Organizations configured"
      ansible.builtin.set_fact:
        __controller_api_organizations: "{{ query(controller_api_plugin, 'organizations',
                                                  host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                  return_all=true, max_objects=query_controller_api_max_objects)
                                         }}"
      no_log: "{{ controller_configuration_object_diff_secure_logging }}"

    - name: "Find the difference of Organizations between what is on the Controller versus curated list."
      ansible.builtin.set_fact:
        __organizations_difference: "{{ query(controller_role_plugin,
                                              api_list=__controller_api_organizations, compare_list=controller_organizations,
                                              with_present=include_present_state, set_absent=true) | flatten
                                     }}"

    - name: "Set list __list_empty_orgs when protect_not_empty_orgs"
      ansible.builtin.set_fact:
        __list_empty_orgs: "{{ __list_empty_orgs | default([]) + [__organizations_difference_list_empty_item.name] }}"
      loop: "{{ __organizations_difference }}"
      loop_control:
        loop_var: __organizations_difference_list_empty_item
      no_log: "{{ controller_configuration_object_diff_secure_logging }}"
      when:
        - protect_not_empty_orgs is defined
        - protect_not_empty_orgs
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/users/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/admins/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/inventories/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/teams/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/projects/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/job_templates/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0
        - query(controller_api_plugin, 'api/' + controller_api_version + '/organizations/' + (__organizations_difference_list_empty_item.name | urlencode) + '/workflow_job_templates/',
                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) | length == 0

    - name: "Set Organization differences"
      ansible.builtin.set_fact:
        __controller_organizations: "{{ __controller_organizations | default([]) + [__organizations_difference_item] }}"
      loop: "{{ __organizations_difference }}"
      loop_control:
        loop_var: __organizations_difference_item
      when:
        - __organizations_difference is defined
        - protect_not_empty_orgs is not defined or not protect_not_empty_orgs or (__list_empty_orgs is defined and __organizations_difference_item.name in __list_empty_orgs)

    - name: "Set organization's list to be configured"
      ansible.builtin.set_fact:
        controller_organizations: "{{ __controller_organizations | default([]) }}"
...
