---
- name: Get the organization ID
  ansible.builtin.set_fact:
    __controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                             query_params={'name': orgs},
                                             host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                   }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Get the API list of all Projects in Organization {{ orgs }}"
  ansible.builtin.set_fact:
    __controller_api_projects: "{{ query(controller_api_plugin, 'projects',
                                         query_params={'organization': __controller_organization_id.id},
                                         host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                         return_all=true, max_objects=query_controller_api_max_objects)
                                }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Find the difference of Project between what is on the Controller versus CasC on SCM"
  ansible.builtin.set_fact:
    __projects_difference: "{{ query(controller_role_plugin,
                                     api_list=__controller_api_projects, compare_list=controller_projects,
                                     with_present=include_present_state, set_absent=true) | flatten
                            }}"

- name: "Set project's list to be configured"
  ansible.builtin.set_fact:
    controller_projects: "{{ __projects_difference }}"
...
