---
- name: "OBJECT DIFF: Get the current controller user to determine if it is super-admin"
  ansible.builtin.set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup(controller_api_plugin, 'users',
                                                              query_params={'username': controller_username},
                                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=false)
                                                   }}"

- name: "Role differences (block)"
  block:

    - name: "OBJECT DIFF: Get the API list of all roles"
      ansible.builtin.set_fact:
        __controller_api_roles: "{{ query(controller_api_plugin, 'roles',
                                          host=controller_hostname, username=controller_username,
                                          password=controller_password, verify_ssl=false)
                                 }}"

    - name: "OBJECT DIFF: Find the difference of Roles between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __roles_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                        api_list=__controller_api_roles, compare_list=controller_roles,
                                        with_present=false, set_absent=true)
                             }}"

    - name: "OBJECT DIFF: Sets differences between Roles what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        controller_roles: "{{ __roles_difference }}"

  when:
    - __controller_api_current_user_check_is_admin.is_superuser
...
