---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_hostname: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# ah_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the Automation Hub ee repository
ah_ee_registries: []
# possible fields:
#  - name: "registry" # mandatory
#    url: registry.redhat.io # mandatory
#    username: myuser
#    password: mypass
#    tls_validation: false
#    proxy_url: myproxy.example.com:8080
#    proxy_username: proxyadmin
#    proxy_password: proxyadmin
#    download_concurrency: 100
#    rate_limit: 5
#    state: present

ah_configuration_ee_registry_secure_logging: "{{ ah_configuration_secure_logging | default(false) }}"
ah_configuration_ee_registry_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
ah_configuration_ee_registry_async_delay: "{{ ah_configuration_async_delay | default(1) }}"
...
