---

# These are the default variables common to most gateway_configuration roles
# You shouldn't need to define them again and again but they should be defined
# aap_hostname: "{{ inventory_hostname }}"
# gateway_token: ""
# aap_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the authenticator maps
gateway_authenticator_maps: []
gateway_authenticator_maps_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
gateway_authenticator_maps_async_retries: "{{ aap_configuration_async_retries | default(30) }}"
gateway_authenticator_maps_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
gateway_authenticator_maps_loop_delay: "{{ aap_configuration_loop_delay | default(0) }}"
aap_configuration_async_dir:
...
