---
argument_specs:
  main:
    short_description: An Ansible Role to call other roles to create objects on Ansible eda.
    options:
      eda_configuration_dispatcher_roles:
        default:
          - {role: user, var: eda_users, tags: user}
          - {role: credential, var: eda_credentials, tags: credential}
          - {role: user_token, var: eda_user_tokens, tags: user_token}
          - {role: project, var: eda_projects, tags: project}
          - {role: project_sync, var: eda_projects, tags: project_sync}
          - {role: decision_environment, var: eda_decision_environments, tags: decision_environment}
          - {role: rulebook_activation, var: eda_rulebook_activations, tags: rulebook_activation}
        required: false
        description: List of roles, variables and tags to run through
        type: list
        elements: dict
        options:
          role:
            required: true
            description: Name of role from this collection to call
            type: str
          var:
            required: true
            description: Name of variable to be passed to the role
            type: str
          tags:
            required: false
            description: Tags to be applied to the role so tagging can be used to run only part of a playbook


      # Async variables
      eda_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      eda_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.


      # No_log variables
      eda_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      eda_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      eda_hostname:
        default: None
        required: false
        description: URL to the Ansible EDA Server.
        type: str
      eda_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible EDA Server's SSL certificate.
        type: str
      controller_username:
        default: None
        required: false
        description: Admin User on the Ansible EDA Server. Either username / password or oauthtoken need to be specified.
        type: str
      controller_password:
        default: None
        required: false
        description: eda Admin User's password on the Ansible EDA Server. This should be stored in an Ansible Vault at vars/eda-secrets.yml or elsewhere and called from a parent playbook.
        type: str
...
