---
galaxy_info:
  role_name: "dispatch"
  author: "Sean Sullivan"
  description: "An Ansible Role which launches all of the roles within the gateway_configuration Collection."
  company: "Red Hat"

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  license: "GPLv3"

  min_ansible_version: "2.14"

  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "gateway"
    - "aap"
    - "configuration"
    - "dispatch"

dependencies: []
...
