---
argument_specs:
  main:
    short_description: An Ansible Role to create credential types on Ansible Controller.
    options:
      controller_credential_types:
        description: Data structure describing your credential_types
        type: list
        elements: dict
        # options:
        #   name:
        #     type: str
        #     required: true
        #     description: Name of Credential Type
        #   description:
        #     type: str
        #     required: false
        #     description: The description of the credential type to give more detail about it.
        #   injectors:
        #     type: dict
        #     required: false
        #     description: Enter injectors using either JSON or YAML syntax. Refer to the Ansible controller documentation for example syntax. See below on proper formatting.
        #   inputs:
        #     type: dict
        #     required: false
        #     description: Enter inputs using either JSON or YAML syntax. Refer to the Ansible controller documentation for example syntax.
        #   kind:
        #     default: cloud
        #     type: str
        #     required: false
        #     choices:
        #       - 'ssh'
        #       - 'vault'
        #       - 'net'
        #       - 'scm'
        #       - 'cloud'
        #       - 'insights'
        #     description: The type of credential type being added. Note that only cloud and net can be used for creating credential types.
        #   state:
        #     default: "{{ controller_state | default('present') }}"
        #     type: str
        #     required: false
        #     description: Desired state of the resource.

      # Async variables
      controller_configuration_credential_types_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      controller_configuration_credential_types_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.


      # No_log variables
      controller_configuration_credential_types_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Platform Admin User's password on the Server.  This should be stored in an Ansible Vault at vars/platform-secrets.yml or elsewhere and called from a parent playbook.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
