---
galaxy_info:
  role_name: gateway_applications
  author: John Westcott IV
  description: An Ansible Role to create applications in Ansible gateway.
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  license: GPLv3

  min_ansible_version: 2.16.0

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - gateway
    - aap
    - configuration
    - application
    - applications

dependencies:
  - role: global_vars
...
