---
- name: "Get list of files inside {{ filetree_controller_applications }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_applications }}"
    file_type: file
    recurse: true
  register: __list_files_controller_applications

- name: "Read Applications definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_applications_definitions_item.path }}"
  loop: "{{ __list_files_controller_applications.files }}"
  loop_control:
    loop_var: __read_applications_definitions_item
  register: __contents_filetree_controller_applications
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_applications"

- name: "Populate Applications list"
  ansible.builtin.set_fact:
    __populate_controller_applications: "{{ (__populate_controller_applications | default([])) + __populate_applications_list_item.ansible_facts.controller_applications }}"
  loop: "{{ __contents_filetree_controller_applications.results }}"
  loop_control:
    loop_var: __populate_applications_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_applications.results is defined and __populate_applications_list_item.ansible_facts.controller_applications is defined

- name: "Set Applications Data Structure"
  ansible.builtin.set_fact:
    controller_applications: "{{ __populate_controller_applications }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_applications is defined
...
