---
- name: "Get list of files inside {{ filetree_controller_credential_input_sources }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_credential_input_sources }}"
    file_type: file
    recurse: true
  register: __list_files_controller_credential_input_sources

- name: "Read Credential Input Sources definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_input_sources_definitions_item.path }}"
  loop: "{{ __list_files_controller_credential_input_sources.files }}"
  loop_control:
    loop_var: __read_input_sources_definitions_item
  register: __contents_filetree_controller_credential_input_sources
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_credential_input_sources"

- name: "Populate Credential Input Sources list"
  ansible.builtin.set_fact:
    __populate_controller_credential_input_sources: "{{ (__populate_controller_credential_input_sources | default([])) + __populate_input_sources_list_item.ansible_facts.controller_credential_input_sources }}"
  loop: "{{ __contents_filetree_controller_credential_input_sources.results }}"
  loop_control:
    loop_var: __populate_input_sources_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_credential_input_sources.results is defined and __populate_input_sources_list_item.ansible_facts.controller_credential_input_sources is defined

- name: "Set Credential Input Sources Data Structure"
  ansible.builtin.set_fact:
    controller_credential_input_sources: "{{ __populate_controller_credential_input_sources }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_credential_input_sources is defined
...
