---
- name: "Get list of files inside {{ filetree_controller_credentials }}"
  find:
    paths: "{{ filetree_controller_credentials }}"
    file_type: file
    recurse: yes
  register: __list_files_controller_credentials

- name: "Read Credentials definitions"
  include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_credentials.files }}"
  register: __contents_filetree_controller_credentials

- name: "Populate Credentials list"
  set_fact:
    __populate_controller_credentials: "{{ (__populate_controller_credentials | default([])) + item.ansible_facts.controller_credentials }}"
  loop: "{{ __contents_filetree_controller_credentials.results }}"
  when: __contents_filetree_controller_credentials.results is defined and item.ansible_facts.controller_credentials is defined

- name: "Set Credentials Data Structure"
  set_fact:
    controller_credentials: "{{ __populate_controller_credentials }}"
  when: __populate_controller_credentials is defined
...
