---
- name: "Get list of files inside {{ filetree_controller_groups }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_groups }}"
    file_type: file
    recurse: true
  register: __list_files_controller_groups

- name: "Read Groups definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_groups_definitions_item.path }}"
  loop: "{{ __list_files_controller_groups.files }}"
  loop_control:
    loop_var: __read_groups_definitions_item
  register: __contents_filetree_controller_groups
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_groups"

- name: "Populate Groups list"
  ansible.builtin.set_fact:
    __populate_controller_groups: "{{ (__populate_controller_groups | default([])) + __populate_groups_list_item.ansible_facts.controller_groups }}"
  loop: "{{ __contents_filetree_controller_groups.results }}"
  loop_control:
    loop_var: __populate_groups_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_groups.results is defined and __populate_groups_list_item.ansible_facts.controller_groups is defined

- name: "Set Groups Data Structure"
  ansible.builtin.set_fact:
    controller_groups: "{{ __populate_controller_groups }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_groups is defined
...
