---
- name: "Get list of files inside {{ filetree_controller_instance_groups }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_instance_groups }}"
    file_type: file
    recurse: true
  register: __list_files_controller_instance_groups

- name: "Read Instance Groups definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_instance_groups_definitions_item.path }}"
  loop: "{{ __list_files_controller_instance_groups.files }}"
  loop_control:
    loop_var: __read_instance_groups_definitions_item
  register: __contents_filetree_controller_instance_groups
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_instance_groups"

- name: "Populate Instance Groups list"
  ansible.builtin.set_fact:
    __populate_controller_instance_groups: "{{ (__populate_controller_instance_groups | default([])) + __populate_instance_groups_list_item.ansible_facts.controller_instance_groups }}"
  loop: "{{ __contents_filetree_controller_instance_groups.results }}"
  loop_control:
    loop_var: __populate_instance_groups_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_instance_groups.results is defined and __populate_instance_groups_list_item.ansible_facts.controller_instance_groups is defined

- name: "Segregated Instance Groups list when controller_location is defined"
  when: controller_location is defined and __populate_controller_instance_groups is defined
  block:
    - name: "Populate Instance Groups list by _common objects"
      ansible.builtin.set_fact:
        __populate_controller_instance_groups_common: "{{ (__populate_controller_instance_groups_common | default([])) + [__populate_instance_groups_list_common_item] }}"
      loop: "{{ __populate_controller_instance_groups }}"
      loop_control:
        loop_var: __populate_instance_groups_list_common_item
      no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
      when: "__populate_instance_groups_list_common_item.controller_location is not defined"

    - name: "Populate Instance Groups list by __site objects"
      ansible.builtin.set_fact:
        __populate_controller_instance_groups_site: "{{ (__populate_controller_instance_groups_site | default([])) + [__populate_instance_groups_list_site_item] }}"
      loop: "{{ __populate_controller_instance_groups }}"
      loop_control:
        loop_var: __populate_instance_groups_list_site_item
      no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
      when: "__populate_instance_groups_list_site_item.controller_location is defined and __populate_instance_groups_list_site_item.controller_location == controller_location"

    - name: "Concatenate Instance Groups list common + site"
      ansible.builtin.set_fact:
        __populate_controller_instance_groups_total: "{{ __populate_controller_instance_groups_common | default([]) + __populate_controller_instance_groups_site }}"
      no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
      when: __populate_controller_instance_groups_site is defined

    - name: "Set Instance Groups Data Structure common + site concatenated"
      ansible.builtin.set_fact:
        __populate_controller_instance_groups: "{{ __populate_controller_instance_groups_total }}"
      no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
      when: __populate_controller_instance_groups_total is defined

- name: "Set Instance Groups Data Structure"
  ansible.builtin.set_fact:
    controller_instance_groups: "{{ __populate_controller_instance_groups }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_instance_groups is defined
...
