---
- name: "Get list of files inside {{ filetree_controller_inventories }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_inventories }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filetree_contorller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_controller_inventories

- name: "Read Inventories definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_inventories_definitions_item.path }}"
  loop: "{{ __list_files_controller_inventories.files }}"
  loop_control:
    loop_var: __read_inventories_definitions_item
  register: __contents_filetree_controller_inventories
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_inventories"

- name: "Set Inventories Data Structure"
  ansible.builtin.set_fact:
    controller_inventories: >-
      {{
        __contents_filetree_controller_inventories.results |
        rejectattr('ansible_facts.controller_inventories', 'undefined') |
        map(attribute='ansible_facts.controller_inventories') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_inventories.results
...
