---
- name: "Get list of files inside {{ filetree_controller_templates }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_templates }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filltree_contorller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_controller_templates

- name: "Read Job Templates definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_job_templates_definitions_item.path }}"
  loop: "{{ __list_files_controller_templates.files }}"
  loop_control:
    loop_var: __read_job_templates_definitions_item
  register: __contents_filetree_controller_templates
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_templates"

- name: "Set Job Templates Data Structure"
  ansible.builtin.set_fact:
    controller_templates: >-
      {{
        __contents_filetree_controller_templates.results |
        rejectattr('ansible_facts.controller_templates', 'undefined') |
        map(attribute='ansible_facts.controller_templates') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_templates.results
...
