---
- name: "Get list of files inside {{ filetree_controller_templates }}"
  find:
    paths: "{{ filetree_controller_templates }}"
    file_type: file
    recurse: true
  register: __list_files_controller_templates

- name: "Read Job Templates definitions"
  include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_templates.files }}"
  register: __contents_filetree_controller_templates

- name: "Populate Job Templates list"
  set_fact:
    __populate_controller_job_templates: "{{ (__populate_controller_job_templates | default([])) + item.ansible_facts.controller_templates }}"
  loop: "{{ __contents_filetree_controller_templates.results }}"
  when: __contents_filetree_controller_templates.results is defined and item.ansible_facts.controller_templates is defined

- name: "Set Job Templates Data Structure"
  set_fact:
    controller_templates: "{{ __populate_controller_job_templates }}"
  when: __populate_controller_job_templates is defined
...
