---
- name: "Get list of files inside {{ filetree_controller_organizations }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_organizations }}"
    file_type: file
    recurse: true
  register: __list_files_controller_organizations

- name: "Read Organization definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_organizations_definitions_item.path }}"
  loop: "{{ __list_files_controller_organizations.files }}"
  loop_control:
    loop_var: __read_organizations_definitions_item
  register: __contents_filetree_controller_organizations
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_organizations"

- name: "Populate Organizations list"
  ansible.builtin.set_fact:
    __populate_controller_organizations: "{{ (__populate_controller_organizations | default([])) + __populate_organizations_list_item.ansible_facts.controller_organizations }}"
  loop: "{{ __contents_filetree_controller_organizations.results }}"
  loop_control:
    loop_var: __populate_organizations_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_organizations.results is defined and __populate_organizations_list_item.ansible_facts.controller_organizations is defined

- name: "Set Organization Data Structure"
  ansible.builtin.set_fact:
    controller_organizations: "{{ __populate_controller_organizations }}"
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __populate_controller_organizations is defined
...
