---
- name: "Get list of files inside {{ filetree_controller_projects }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_projects }}"
    file_type: file
    patterns: "{{ filetree_controller_include | default(omit) }}"
    excludes: "{{ filltree_contorller_exclude | default(omit) }}"
    use_regex: "{{ filetree_controller_regex | default(false) }}"
    recurse: true
  register: __list_files_controller_projects

- name: "Read Projects definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_projects_definitions_item.path }}"
  loop: "{{ __list_files_controller_projects.files }}"
  loop_control:
    loop_var: __read_projects_definitions_item
  register: __contents_filetree_controller_projects
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_projects"

- name: "Set Projects Data Structure"
  ansible.builtin.set_fact:
    controller_projects: >-
      {{
        __contents_filetree_controller_projects.results |
        rejectattr('ansible_facts.controller_projects', 'undefined') |
        map(attribute='ansible_facts.controller_projects') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_projects.results
...
