---
- name: "Get list of files inside {{ filetree_controller_user_accounts }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_user_accounts }}"
    file_type: file
    recurse: true
  register: __list_files_controller_user_accounts

- name: "Read User Accounts definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_user_accounts_definitions_item.path }}"
  loop: "{{ __list_files_controller_user_accounts.files }}"
  loop_control:
    loop_var: __read_user_accounts_definitions_item
  register: __contents_filetree_controller_user_accounts
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_user_accounts"

- name: "Populate User Accounts list"
  ansible.builtin.set_fact:
    __populate_controller_user_accounts: "{{ (__populate_controller_user_accounts | default([])) + __populate_user_accounts_list_item.ansible_facts.controller_user_accounts }}"
  loop: "{{ __contents_filetree_controller_user_accounts.results }}"
  loop_control:
    loop_var: __populate_user_accounts_list_item
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_user_accounts.results is defined and __populate_user_accounts_list_item.ansible_facts.controller_user_accounts is defined

- name: "Set User Accounts Data Structure"
  ansible.builtin.set_fact:
    controller_user_accounts: "{{ __populate_controller_user_accounts }}"
  when: __populate_controller_user_accounts is defined
...
