---
tower_url: ""
tower_user: ""
tower_pass: "" #Put in a vault at vars/tower-secrets.yml when tower_secrets: True
tower_org: ""
tower_verify_ssl: False
tower_secrets: False
tower_proj_name: ""
tower_proj_desc: ""
tower_proj_type: "git"
tower_proj_branch: "master"
tower_proj_url: ""
tower_proj_credential: ""
tower_proj_clean: True
tower_proj_delete: False
tower_proj_update_on_launch: False
