---
argument_specs:
  main:
    short_description: An Ansible Role to create service keys on automation platform gateway.
    options:
      gateway_service_keys:
        description: Data structure describing your service keys
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of the resource
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          is_active:
            type: bool
            description: flag for setting the active state of the Service Key
          service_cluster:
            description: Type of service ("hub", "controller", "eda", "gateway")
            type: str
          algorithm:
            description: |
              algorithm to use for this Service Key
            choices: [HS256, HS384, HS512]
          secret:
            type: str
            description: |
              secret to use for this Service Key
              required when creating new Service Key, non-editable
          secret_length:
            type: int
            description: |
              Number of random bytes in the secret
          mark_previous_inactive:
            type: str
            description: |
              If true any other secret keys for this service will become inactive
          state:
            default: "{{ platform_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      gateway_service_keys_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_service_keys_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      gateway_service_keys_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
