---
gateway_configuration_dispatcher_roles:
  - role: gateway_authenticators
    var: authenticators_list
    tags: authenticators
  - role: gateway_authenticator_maps
    var: authenticator_maps_list
    tags: authenticator_maps
  - role: gateway_settings
    var: settings_list
    tags: settings
  - role: gateway_http_ports
    var: http_ports_list
    tags: http_ports
  - role: gateway_organizations
    var: controller_organizations
    tags: organizations
  - role: gateway_service_clusters
    var: service_clusters_list
    tags: service_clusters
  - role: gateway_service_keys
    var: service_keys_list
    tags: service_keys
  - role: gateway_service_nodes
    var: service_nodes_list
    tags: service_nodes
  - role: gateway_services
    var: services_list
    tags: services
  - role: gateway_role_user_assignments
    var: role_user_assignments_list
    tags: role_user_assignments
  - role: gateway_routes
    var: routes_list
    tags: routes
  - role: gateway_teams
    var: teams_list
    tags: teams
ah_configuration_dispatcher_roles:
  - role: pah_namespace
    var: ah_namespaces
    tags: namespaces
  - role: pah_collection
    var: ah_collections
    tags: collections
  - role: pah_ee_registry
    var: ah_ee_registries
    tags: registries
  - role: pah_ee_repository
    var: ah_ee_repositories
    tags: repos
  - role: pah_ee_repository_sync
    var: ah_ee_repository_sync
    tags: reposync
  - role: pah_ee_image
    var: ah_ee_images
    tags: images
  - role: pah_ee_registry_index
    var: ah_ee_registries
    tags: indices
  - role: pah_ee_registry_sync
    var: ah_ee_registries
    tags: regsync
  - role: pah_collection_remote
    var: ah_collection_remotes
    tags: collectionremote
  - role: pah_collection_repository
    var: ah_collection_repositories
    tags: collectionsrep
  - role: pah_collection_repository_sync
    var: ah_collection_repositories
    tags: collectionsrepsync
controller_configuration_dispatcher_roles:
  - role: controller_settings
    var: controller_settings
    tags: settings
  - role: controller_organizations
    var: controller_organizations
    tags: organizations
    assign_galaxy_credentials_to_org: false
    assign_default_ee_to_org: false
    assign_notification_templates_to_org: false
  - role: controller_instances
    var: controller_instances
    tags: instances
  - role: controller_instance_groups
    var: controller_instance_groups
    tags: instance_groups
  - role: controller_labels
    var: controller_labels
    tags: labels
  - role: controller_credential_types
    var: controller_credential_types
    tags: credential_types
  - role: controller_credentials
    var: controller_credentials
    tags: credentials
  - role: controller_credential_input_sources
    var: controller_credential_input_sources
    tags: credential_input_sources
  - role: controller_execution_environments
    var: controller_execution_environments
    tags: execution_environments
  - role: controller_notification_templates
    var: controller_notifications
    tags: notification_templates
  - role: controller_organizations
    var: controller_organizations
    tags: organizations
    assign_galaxy_credentials_to_org: true
    assign_default_ee_to_org: true
    assign_notification_templates_to_org: true
  - role: controller_projects
    var: controller_projects
    tags: projects
  - role: controller_inventories
    var: controller_inventories
    tags: inventories
  - role: controller_inventory_sources
    var: controller_inventory_sources
    tags: inventory_sources
  - role: controller_inventory_source_update
    var: controller_inventory_sources
    tags: inventory_sources
  - role: controller_hosts
    var: controller_hosts
    tags: hosts
  - role: controller_bulk_host_create
    var: controller_bulk_hosts
    tags: bulk_hosts
  - role: controller_job_templates
    var: controller_templates
    tags: job_templates
  - role: controller_workflow_job_templates
    var: controller_workflows
    tags: workflow_job_templates
  - role: controller_schedules
    var: controller_schedules
    tags: schedules
  - role: controller_job_launch
    var: controller_launch_jobs
    tags: job_launch
  - role: controller_workflow_launch
    var: controller_workflow_launch_jobs
    tags: workflow_launch
eda_configuration_dispatcher_roles:
  - role: eda_credentials
    var: eda_credentials
    tags: credential
  - role: eda_controller_tokens
    var: eda_controller_tokens
    tags: controller_token
  - role: eda_projects
    var: eda_projects
    tags: project
  # - role: eda_project_sync
  #   var: eda_projects
  #   tags: project_sync
  - role: eda_decision_environments
    var: eda_decision_environments
    tags: decision_environment
  - role: eda_rulebook_activations
    var: eda_rulebook_activations
    tags: rulebook_activation

platform_configuration_dispatcher_roles: >
  {{ gateway_configuration_dispatcher_roles
   + ah_configuration_dispatcher_roles
   + controller_configuration_dispatcher_roles
   + eda_configuration_dispatcher_roles
  }}

...
