---
- name: Service Nodes | Configuration # noqa fqcn[action-core]
  ansible.platform.service_node:
    name: "{{ __gateway_service_nodes_item.name | mandatory }}"
    new_name: "{{ __gateway_service_nodes_item.new_name | default(omit) }}"
    address: "{{ __gateway_service_nodes_item.address | default(omit) }}"
    service_cluster: "{{ __gateway_service_nodes_item.service_cluster | default(omit) }}"
    tags: "{{ __gateway_service_nodes_item.tags | default(omit) }}"
    state: "{{ __gateway_service_nodes_item.state | default(platform_state | default(omit, true)) }}"

    # Role Standard Options
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ gateway_service_nodes }}"
  loop_control:
    loop_var: __gateway_service_nodes_item
    label: "{{ __operation.verb }} the label {{ __gateway_service_nodes_item.name }} to Controller"
    pause: "{{ gateway_service_nodes_loop_delay }}"
  no_log: "{{ service_nodes_secure_logging }}"
  async: 1000
  poll: 0
  register: __gateway_service_nodes_job_async
  changed_when: not __gateway_service_nodes_job_async.changed
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir | default(omit) }}"

- name: Service Nodes | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_service_nodes_job_async_results_item.ansible_job_id }}"
  register: __gateway_service_nodes_job_async_result
  until: __gateway_service_nodes_job_async_result.finished
  retries: "{{ service_nodes_async_retries }}"
  delay: "{{ service_nodes_async_delay }}"
  loop: "{{ __gateway_service_nodes_job_async.results }}"
  loop_control:
    loop_var: __gateway_service_nodes_job_async_results_item
    label: "{{ __operation.verb }} Label {{ __gateway_service_nodes_job_async_results_item.__gateway_service_nodes_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __gateway_service_nodes_job_async_results_item.ansible_job_id is defined
  no_log: "{{ service_nodes_secure_logging }}"
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir | default(omit) }}"
...
