---
argument_specs:
  main:
    short_description: An Ansible Role to create inventories on Ansible Controller.
    options:
      controller_inventories:
        description: Data structure describing your inventories
        type: list
        elements: dict
        # options:
        #   name:
        #     required: true
        #     type: str
        #     description: Name of inventory
        #   copy_from:
        #     required: false
        #     type: str
        #     description: Name or id to copy the inventory from. This will copy an existing inventory and change any parameters supplied.
        #   description:
        #     required: false
        #     type: str
        #     description: Description to use for the inventory.
        #   organization:
        #     required: false
        #     type: str
        #     description: Organization this inventory belongs to.
        #   instance_groups:
        #     required: false
        #     type: list
        #     elements: str
        #     description: list of Instance Groups for this Inventory to run on.
        #   variables:
        #     required: false
        #     type: dict
        #     description: Variables for the inventory.
        #   kind:
        #     default: ""
        #     required: false
        #     type: str
        #     choices:
        #       - ""
        #       - smart
        #     description: The kind of inventory. Currently choices are '' and 'smart'
        #   host_filter:
        #     default: false
        #     required: false
        #     type: str
        #     description: The host filter field, useful only when 'kind=smart'
        #   prevent_instance_group_fallback:
        #     default: false
        #     required: false
        #     type: bool
        #     description: Prevent falling back to instance groups set on the organization
        #   state:
        #     default: "{{ controller_state | default('present') }}"
        #     required: false
        #     type: str
        #     description: Desired state of the resource.

      # Async variables
      controller_configuration_inventories_async_retries:
        default: "{{ platform_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      platform_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      controller_configuration_inventories_async_delay:
        default: "{{ platform_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      platform_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      platform_configuration_async_dir:
        default: null
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.


      # No_log variables
      controller_configuration_inventories_secure_logging:
        default: "{{ platform_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      platform_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      platform_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      platform_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      platform_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      platform_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      platform_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
