# User may add tower auth creds to this file and encrypt it using `ansible-vault`
---
controller_hostname: controller.node
controller_username: admin
controller_password: secret123
controller_validate_certs: false
...
