---
- name: Teams | Configuration # noqa fqcn[action-core]
  ansible.platform.team:
    name: "{{ __gateway_teams_item.name | mandatory }}"
    new_name: "{{ __gateway_teams_item.new_name | default(omit) }}"
    description: "{{ __gateway_teams_item.description | default(omit) }}"
    organization: "{{ __gateway_teams_item.organization | default(omit) }}"
    new_organization: "{{ __gateway_teams_item.new_organization | default(omit) }}"
    state: "{{ __gateway_teams_item.state | default(platform_state | default(omit, true)) }}"

    # Role Standard Options
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ aap_teams }}"
  loop_control:
    loop_var: __gateway_teams_item
    label: "{{ __operation.verb }} the label {{ __gateway_teams_item.name }} to Controller"
    pause: "{{ gateway_teams_loop_delay }}"
  no_log: "{{ gateway_teams_secure_logging }}"
  async: 1000
  poll: 0
  register: __gateway_teams_job_async
  changed_when: not __gateway_teams_job_async.changed
  vars:
    __operation: "{{ operation_translate[__gateway_teams_job_async.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir | default(omit) }}"

- name: Teams | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_teams_job_async_results_item.ansible_job_id }}"
  register: __gateway_teams_job_async_result
  until: __gateway_teams_job_async_result.finished
  retries: "{{ gateway_teams_async_retries }}"
  delay: "{{ gateway_teams_async_delay }}"
  loop: "{{ __gateway_teams_job_async.results }}"
  loop_control:
    loop_var: __gateway_teams_job_async_results_item
    label: "{{ __operation.verb }} Label {{ __gateway_teams_job_async_results_item.__gateway_teams_item.name }} | Wait for finish the Label {{ __operation.action }}"
  when: __gateway_teams_job_async_results_item.ansible_job_id is defined
  no_log: "{{ platform_teams_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__gateway_teams_job_async_results_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir | default(omit) }}"
...
