---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false

# These are the default variables specific to the controller_settings role

# list of dicts (or a single dict) describing the Tower settings
controller_settings: []
# possible fields:
# - settings:  # either this field or name/value is mandatory
#    SETTING_NAME: setting_value
# - name: "SETTING_NAME"
#  value: SETTING_VALUE

controller_configuration_settings_secure_logging: "{{controller_configuration_secure_logging | default('false')}}"
controller_configuration_settings_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_settings_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
