---

# Launch Tower Job
- name: Launch a Tower Job
  awx.awx.tower_job_launch:
    name:                     "{{ __job_launch_item.name | mandatory }}"
    job_type:                 "{{ __job_launch_item.job_type | default(omit) }}"
    inventory:                "{{ __job_launch_item.inventory | default(omit) }}"
    credentials:              "{{ __job_launch_item.credentials | default(omit) }}"
    extra_vars:               "{{ __job_launch_item.extra_vars | default(omit) }}"
    limit:                    "{{ __job_launch_item.limit | default(omit) }}"
    tags:                     "{{ __job_launch_item.tags | default(omit) }}"
    scm_branch:               "{{ __job_launch_item.scm_branch | default(omit) }}"
    skip_tags:                "{{ __job_launch_item.skip_tags | default(omit) }}"
    verbosity:                "{{ __job_launch_item.verbosity | default(omit) }}"
    diff_mode:                "{{ __job_launch_item.diff_mode | default(omit) }}"
    credential_passwords:     "{{ __job_launch_item.credential_passwords | default(omit) }}"
    wait:                     "{{ __job_launch_item.wait | default(omit) }}"
    interval:                 "{{ __job_launch_item.interval | default(omit) }}"
    timeout:                  "{{ __job_launch_item.timeout | default(omit) }}"

    # Role Standard Options
    tower_username:     "{{ tower_username | default(omit) }}"
    tower_password:     "{{ tower_password | default(omit) }}"
    tower_oauthtoken:   "{{ tower_oauthtoken | default(omit) }}"
    tower_host:         "{{ tower_hostname }}"
    tower_config_file:  "{{ tower_config_file | default(omit) }}"
    validate_certs:     "{{ tower_validate_certs | default('true') }}"
  loop: "{{ tower_launch_jobs }}"
  loop_control:
    loop_var: "__job_launch_item"
  no_log: "{{ tower_configuration_job_launch_secure_logging }}"
  register: launched_tower_jobs
  when: tower_launch_jobs is defined
