---
- name: Playbook to configure ansible tower post installation
  hosts: localhost
  connection: local
  vars:
    workflow_job_templates_secure_logging: false
  # Define following vars here, or in tower_configs/tower_auth.yml
  # tower_hostname: ansible-tower-web-svc-test-project.example.com
  # tower_username: admin
  # tower_password: changeme
  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs_export_model
        ignore_files: [README.md]
        extensions: ["yml"]
  roles:
    - {role: organizations, when: tower_organizations is defined, tags: organizations}
    - {role: workflow_job_templates, when: tower_workflows is defined}
    - {role: notifications, when: tower_notifications is defined, tags: notifications}
