---
argument_specs:
  main:
    short_description: An Ansible Role to create users on automation platform gateway.
    options:
      aap_user_accounts:
        description: Data structure describing your users
        type: list
        required: true
        elements: dict
        # options:
        #   username:
        #     required: true
        #     type: str
        #     description: Username of user
        #   password:
        #     required: true
        #     type: str
        #     description: Password of user, defaults to "{{ users_default_password }}" if not set
        #   email:
        #     required: false
        #     type: str
        #     description: email of the user
        #   first_name:
        #     required: false
        #     type: str
        #     description: first_name of the user
        #   last_name:
        #     required: false
        #     type: str
        #     description: last_name of the user
        #   is_superuser:
        #     default: false
        #     required: false
        #     type: bool
        #     description: Whether the user is a superuser
        #   update_secrets:
        #     default: true
        #     required: false
        #     type: bool
        #     description: >
        #       True will always change password if user specifies password, even if API gives $encrypted$ for password.
        #       False will only set the password if other values change too.
        #   organization:
        #     required: false
        #     type: str
        #     description: Organization this user belongs to.
        #   authenticators:
        #     required: false
        #     type: list
        #     description: Authenticators this user is associated with
        #   authenticator_uid:
        #     required: false
        #     type: str
        #     description: The uid associated with the users authenticators
        #   state:
        #     default: "{{ platform_state | default('present') }}"
        #     required: false
        #     type: str
        #     description: Desired state of the resource.

      users_default_password:
        default: None
        required: false
        type: str
        description: Global variable to set the password for all users.

      # Async variables
      gateway_users_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_users_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      gateway_users_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(true) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
