---
# Cancel a Controller Job
- name: Cancel a Controller Job
  job_cancel:
    job_id:                   "{{ __controller_jobs_cancel_item.id | mandatory }}"
    fail_if_not_running:      "{{ __controller_jobs_cancel_item.fail_if_not_running | default(omit) }}"

    # Role Standard Options
    controller_username:     "{{ platform_username | default(omit, true) }}"
    controller_password:     "{{ platform_password | default(omit, true) }}"
    controller_oauthtoken:   "{{ platform_oauthtoken | default(omit, true) }}"
    request_timeout:         "{{ platform_request_timeout | default(omit, true) }}"
    controller_host:         "{{ controller_host | default(omit, true) }}"
    validate_certs:     "{{ platform_validate_certs | default(omit) }}"
  loop: "{{ controller_cancel_jobs }}"
  loop_control:
    loop_var: "__controller_jobs_cancel_item"
  no_log: "{{ controller_configuration_jobs_cancel_secure_logging }}"
  when: controller_cancel_jobs is defined
...
