---
# defaults file for object_diff

# populate_controller_api_user_accounts_without_external_accounts
drop_user_external_accounts: false
query_controller_api_max_objects: 10000

# Automation Controller Object Lists
controller_settings: []
controller_organizations: []
controller_labels: []
controller_user_accounts: []
controller_teams: []
controller_credential_types: []
controller_credentials: []
controller_credential_input_sources: []
controller_notifications: []
controller_projects: []
controller_execution_environments: []
controller_applications: []
controller_inventories: []
controller_inventory_sources: []
controller_instance_groups: []
controller_hosts: []
controller_groups: []
controller_templates: []
controller_workflows: []
controller_schedules: []
controller_roles: []

# object_diff tasks name
controller_configuration_object_diff_tasks:
  - {name: schedules, var: controller_schedules, tags: schedules}
  - {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
  - {name: job_templates, var: controller_templates, tags: job_templates}
  - {name: roles, var: controller_roles, tags: roles}
  - {name: teams, var: controller_teams, tags: teams}
  - {name: user_accounts, var: controller_user_accounts, tags: users}
  - {name: groups, var: controller_groups, tags: groups}
  - {name: hosts, var: controller_hosts, tags: hosts}
  - {name: applications, var: controller_applications, tags: applications}
  - {name: execution_environments, var: controller_execution_environments, tags: execution_environments}
  - {name: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
  - {name: inventories, var: controller_inventories, tags: inventories}
  - {name: projects, var: controller_projects, tags: projects}
  - {name: notification_templates, var: controller_notification_templates, tags: notification_templates}
  - {name: credentials, var: controller_credentials, tags: credentials}
  - {name: credential_types, var: controller_credential_types, tags: credential_types}
  - {name: organizations, var: controller_organizations, tags: organizations}
  - {name: instance_groups, var: controller_instance_groups, tags: instance_groups}

controller_configuration_object_diff_secure_logging: "{{ controller_configuration_secure_logging | default(true) }}"

controller_api_version: "v2"

include_present_state: false
...
