---
name: Test roles and modules with galaxy_ng

on:
  workflow_call:
    inputs:
      galaxy_ng_version:
        description: The version to pull of galaxy_ng
        required: true
        type: string
      ci_workflow:
        description: The workflow name
        required: true
        type: string
      gh_ref:
        description: The ref in the repository to pull
        required: false
        default: devel
        type: string
    secrets:
      redhat_catalog_username:
        description: Username for Red Hat Catalog
        required: true
      redhat_catalog_password:
        description: Password for Red Hat Catalog
        required: true

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.gh_ref }}

      - name: Move ansible.cfg to root
        run: mv .github/files/ansible.cfg .

      - name: Build and install the collection
        id: build
        uses: redhat-cop/ansible_collections_tooling/actions/build_ansible_collection@main
        with:
          collection_namespace: galaxy
          collection_name: galaxy
          collection_version: 1.0.0
          collection_repo: https://github.com/ansible/galaxy_collection

      - name: "Checkout galaxy_ng"
        uses: actions/checkout@v2
        with:
          repository: ansible/galaxy_ng
          path: galaxy_ng
          ref: ${{ inputs.galaxy_ng_version }}

      - name: (Linux) Install docker compose
        run: |
          curl -L -o /tmp/docker-compose https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64
          install /tmp/docker-compose /usr/local/bin/

      # Note: COMPOSE_INTERACTIVE_NO_CLI=1 is required for oci-env to work correctly when there's no interactive terminal
      - name: Set environment variables
        working-directory: galaxy_ng
        run: |
          echo "OCI_ENV_PATH=${GITHUB_WORKSPACE}/oci_env" >> $GITHUB_ENV
          echo "COMPOSE_INTERACTIVE_NO_CLI=1" >> $GITHUB_ENV
          echo "OCI_VERBOSE=1" >> $GITHUB_ENV
          echo "GH_DUMP_LOGS=1" >> $GITHUB_ENV
          echo "GH_TEARDOWN=0" >> $GITHUB_ENV
          echo "AH_HOST=http://localhost:8080/" >> $GITHUB_ENV
          echo "AH_USERNAME=admin" >> $GITHUB_ENV
          echo "AH_PASSWORD=admin" >> $GITHUB_ENV
          echo "AH_LOGOUT_PATH=/api/gateway/v1/logout/" >> $GITHUB_ENV

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: setup oci-env
        working-directory: galaxy_ng
        run: |
          git clone https://github.com/pulp/oci_env.git $OCI_ENV_PATH
          pip install -e $OCI_ENV_PATH/client/
          mkdir $OCI_ENV_PATH/db_backup/

      - name: Move ci cfg to oci
        run: mv .github/files/ci_dab_jwt.py ./galaxy_ng/dev/oci_env_integration/actions/ci_dab_jwt.py

      - name: Stand up galaxy_ng
        working-directory: galaxy_ng
        run: python3 dev/oci_env_integration/actions/ci_dab_jwt.py

      - name: "Perform playbook collection tests"
        run: ansible-playbook tests/playbooks/testing_collections_playbook.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }} -e git_repo_name=${{ github.event.repository.name }} -e ci_workflow=${{ inputs.ci_workflow }}

      - name: "Perform collection repository tests"
        run: ansible-playbook tests/playbooks/testing_collections_repos.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }} -e ci_workflow=${{ inputs.ci_workflow }}

      - name: "Perform playbook repository tests"
        run: ansible-playbook tests/playbooks/testing_playbook_ee_repository.yml -vv -e galaxy_ng_version=${{ inputs.galaxy_ng_version }} -e redhat_catalog_username=${{ secrets.redhat_catalog_username }} -e redhat_catalog_password=${{ secrets.redhat_catalog_password }} -e ci_workflow=${{ inputs.ci_workflow }}
