---
name: Test roles and modules
on: [push, pull_request_target]

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        galaxy_ng_version:
          - stable-4.4
          - stable-4.5
          - stable-4.6
          - stable-4.7
          - master
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      galaxy_ng_version: ${{ matrix.galaxy_ng_version }}
      gh_ref: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets:
      redhat_catalog_username: ${{ secrets.REDHAT_CATALOG_USERNAME }}
      redhat_catalog_password: ${{ secrets.REDHAT_CATALOG_PASSWORD }}
