---
name: Test collection with AWX matrix
on:
  push:
    branches:
    - '*_'
    - devel
    tags:
    - '*_'  # ending underscore for trying things
    - 'v[0-9]+.[0-9]+.[0-9]+'  # final version
    - 'v[0-9]+.[0-9]+.[0-9]+[abrc]+[0-9]+'  # alpha, beta, release candidate (rc)
    - 'v[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'  # development versions
  pull_request:

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        awx_version:
          - devel
          - 22.4.0
          - 22.3.0
          - 21.13.0
          - 21.11.0
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      awx_version: ${{ matrix.awx_version }}
