---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: pre-commit tests


on:
  push:
    branches:
    - '*_'  # ending underscore for trying things
    - devel
    tags:
    - '*_'  # ending underscore for trying things
    - 'v[0-9]+.[0-9]+.[0-9]+'  # final version
    - 'v[0-9]+.[0-9]+.[0-9]+[abrc]+[0-9]+'  # alpha, beta, release candidate (rc)
    - 'v[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'  # development versions
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  pre-commit_and_sanity:
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/pre_commit_and_sanity.yml@main"
    with:
      collection_namespace: infra
      collection_name: aap_configuration
      collection_version: 3.0.0-devel
      collection_repo: https://github.com/redhat-cop/aap_configuration/
      collection_dependencies: awx.awx ansible.eda ansible.hub
...
