---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Yaml and Ansible Lint

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Collections
      run: |
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        pip install --upgrade ansible
        ansible-galaxy collection install -f -r .github/collections/requirements.yml
        sudo cp -a collections/ansible_collections/awx/awx/plugins/. plugins/
        ansible-config view -vvv
    - uses: pre-commit/action@v2.0.0
...
