---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/release_pipeline.yml@main"
    with:
      collection_namespace: infra
      collection_namespace_2: redhat_cop
      collection_name: controller_configuration
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/redhat-cop/controller_configuration/
    secrets:
      galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_APIKEY }}
      infra_api_key: ${{ secrets.GALAXY_INFRA_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
...
