---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    needs:
      - ci_standalone
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/release_pipeline_single.yml@main"
    with:
      collection_namespace: infra
      collection_name: eda_configuration
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/redhat-cop/eda_configuration
      quay_username: redhat_cop
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_INFRA_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
      quay_token: ${{ secrets.quay_token }}

...
