---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        awx_version:
          - devel
          - 21.13.0
          - 21.12.0
          - 21.11.0
          # - 20.1.0 Diabled until working
          # - 19.5.1 Diabled until working
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      awx_version: ${{ matrix.awx_version }}
  release:
    needs:
      - ci_standalone
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/release_pipeline.yml@main"
    with:
      collection_namespace: infra
      collection_namespace_2: redhat_cop
      collection_name: controller_configuration
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/redhat-cop/controller_configuration/
      quay_username: redhat_cop
    secrets:
      galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_APIKEY }}
      infra_api_key: ${{ secrets.GALAXY_INFRA_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
      quay_token: ${{ secrets.quay_token }}
...
