---
name: Test collection against galaxy_ng

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      # Follow the Development Setup guide here:
      # https://github.com/ansible/galaxy_ng/wiki/Development-Setup

      - name: Development Setup
        run: |
          cd .github
          git clone https://github.com/ansible/galaxy_ng.git
          git clone https://github.com/ansible/ansible-hub-ui.git
          cd galaxy_ng
          cat <<EOT >> .compose.env
          COMPOSE_PROFILE=standalone
          DEV_SOURCE_PATH='galaxy_ng'
          ANSIBLE_HUB_UI_PATH='/home/runner/work/ah_configuration/ah_configuration/.github/ansible-hub-ui/'
          EOT
          cat .compose.env
          ./compose build
          docker images
          ./compose up -d postgres redis
          docker container ls
          ls -al
          echo $COMPOSE_PROFILE
          echo $DEV_SOURCE_PATH
          echo $ANSIBLE_HUB_UI_PATH
          ./compose run --rm api manage migrate
          ./compose run --rm -e PULP_FIXTURE_DIRS='["/src/galaxy_ng/dev/automation-hub"]' api manage loaddata initial_data.json
          ./compose up -d

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/testing_playbook.yml
...
