name: Run Test Playbooks AWX

on: [push, pull_request]

jobs:
  Integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Login to RedHat Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RegistryUsername }}
          password: ${{ secrets.RegistryPassword }}


      - name: "Build AWX stack"
        run: cd .github/awxcompose && docker-compose up -d

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '60s'

      - name: "Wait for awx to be alive"
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost/api/v2/ping'
          responseCode: 200
          timeout: 600000  # Wait max 10 mins for response
          interval: 3000

      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r .github/collections/requirements.yml

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '20s'

      - name: "check git connect"
        run: git clone https://github.com/ansible/tower-example.git

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/configure_tower.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password -vvv

      - name: "Perform export model playbook tests"
        run: ansible-playbook playbooks/configure_tower_export_model.yml -e tower_hostname=http://localhost -e tower_username=admin -e tower_password=password
