---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_username: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# aap_validate_certs: false

# These are the default variables specific to the collection role
ah_collections: []
# possible fields:
# - namespace
# - name
# - version
# - path
# - wait
# - auto_approve
# - overwrite_existing
# - state

ah_configuration_collection_secure_logging: "{{ aap_configuration_secure_logging | default(false) }}"
ah_configuration_collection_async_timeout: "{{ aap_configuration_async_timeout | default(1000) }}"
ah_configuration_collection_async_retries: "{{ aap_configuration_async_retries | default(50) }}"
ah_configuration_collection_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
aap_configuration_async_dir: null
...
